import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Every release on file. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /orangebox/changelog · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ ORANGEBOX · changelog",
    title: "Every release on file.",
    stamp: "SHIPPED",
    accent: "cyan",
    rightPrimary: "v1.0.0",
    rightLabel: "current · SHA-256 stamped",
    bottomReceipt: "atomeons.com/orangebox/changelog · CC-BY 4.0",
  });
}
