import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "From prototype to publishing instrument. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /b00kmakor/changelog · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ B00KMAKR · changelog",
    title: "From prototype to publishing instrument.",
    stamp: "SHIPPED",
    accent: "cyan",
    rightPrimary: "v3.2",
    rightLabel: "Mac + Windows · audiobook ready",
    bottomReceipt: "atomeons.com/b00kmakor/changelog · CC-BY 4.0",
  });
}
