import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "The room where the work happens. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /studio · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ studio · the atelier",
    title: "The room where the work happens.",
    stamp: "PERSONAL",
    accent: "cyan",
    rightPrimary: "10",
    rightLabel: "objects · 5 daily rituals",
    bottomReceipt: "atomeons.com/studio · CC-BY 4.0",
  });
}
