import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Where we win. Where we lose. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /compare · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ compare · honest matrices",
    title: "Where we win. Where we lose.",
    stamp: "MATRICES",
    accent: "gold",
    rightPrimary: "3",
    rightLabel: "head-to-head products",
    bottomReceipt: "atomeons.com/compare · CC-BY 4.0",
  });
}
