import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "What we will build · what we will not. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /orangebox/roadmap · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ ORANGEBOX · roadmap",
    title: "What we will build · what we will not.",
    stamp: "BINDING",
    accent: "pulse",
    rightPrimary: "8",
    rightLabel: "anti-roadmap clauses · §4A binding",
    bottomReceipt: "atomeons.com/orangebox/roadmap · CC-BY 4.0",
  });
}
