import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "From internal Oski to public registry. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /skilski/changelog · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ skil.ski · changelog",
    title: "From internal Oski to public registry.",
    stamp: "LIVE v1.0",
    accent: "cyan",
    rightPrimary: "2127",
    rightLabel: "skills indexed · 13 sectors",
    bottomReceipt: "atomeons.com/skilski/changelog · CC-BY 4.0",
  });
}
