import type { Metadata } from "next";
import { GenericPage } from "@/app/_components/generic-page/GenericPage";
import type { ContentPage } from "@/app/_components/generic-page/types";

// Auto-materialized from wf_c1eaafe8-714 (nvidia-tier-50 workflow).
// Generated by .scripts/materialize-nvidia-tier-50.mjs.

const PAGE_DATA: ContentPage = {
  "slug": "layoffs",
  "title": "The AI layoffs tracker",
  "subtitle": "Corporate workforce cuts framed around AI, 2023 to 2026 best-effort",
  "accent": "#FF7A1A",
  "intro": "This page tracks corporate layoffs in 2023, 2024, 2025 and into 2026 where the public statement, the CEO memo, or the SEC filing explicitly invoked artificial intelligence as part of the rationale. The shape borrows from layoffs.fyi — company, date, headcount, source — but adds two things layoffs.fyi does not adjudicate: the AI framing in the company's own words, and an honest tag for whether that framing reflects an AI-driven reduction or whether AI was used to rebrand a conventional cost-cut.\n\nThe distinction matters. A finance-driven RIF that gets a Gemini or Copilot mention in the memo is not the same event as IBM telling Bloomberg it expects to attrite 7,800 back-office roles into automation, or Duolingo cutting contract translators because a transformer can produce passable Spanish glosses for less than the per-string rate. Both happen. Conflating them produces bad analysis in either direction — either over-attributing job loss to AI when the real cause is post-pandemic over-hiring, or under-attributing it when the AI substitution is real and the framing is deliberately vague.\n\nThe numbers below are as of June 2026 best-effort. Headcounts are taken from SEC 8-K filings, official company blog posts, and reporting by major outlets (CNBC, Reuters, Bloomberg, Variety, TechCrunch) where SEC disclosure was not required. Where the public framing and the operational reality diverge, this page says so in plain text. Where we don't know, this page says we don't know. Atomic numbers do not get rounded into narrative.\n\nThis is a research surface, not a campaign. It is built for operators, policy researchers, journalists, and anyone trying to read the AI labor signal through corporate language honestly. The framing language matters because it is now also a competitive positioning move — invoking AI as the reason for a layoff signals to investors that the company is on the right side of the productivity story. That signal is worth reading skeptically.",
  "sections": [
    {
      "heading": "How to read this tracker",
      "kind": "list",
      "body": "Four labels are used throughout. They are interpretive — they reflect a judgment based on the public statement, the operational context, and follow-on hiring patterns. The label is not a verdict on the company. It is a description of how to read the memo.",
      "listItems": [
        "AI-driven — the reduction is operationally tied to substitution by an AI system. IBM's 7,800 back-office attrition target and Duolingo's contract translator cuts are the cleanest examples.",
        "AI-framed — the layoff is real, the AI mention is real, but the underlying driver is post-pandemic over-hiring, ad-market softness, or strategic refocus. Dropbox 2023 sits here — the memo cited 'the AI era' but the company also said growth had slowed and a different skill mix was needed.",
        "AI-adjacent — the cuts happened in the same quarter the company announced large AI capex, but the public memo did not explicitly attribute the layoff to AI. Most of Google's 2024 and 2025 rounds fit this category.",
        "AI-rebranded — the layoff would have happened on cost-cutting grounds alone, and AI is invoked to soften the optics or signal forward strategy. Amazon's 2025 round, which CEO Andy Jassy explicitly told staff was about culture and not AI, is the inverse of this — a case where the company actively refused the AI framing."
      ]
    },
    {
      "heading": "The top of the table, 2023 to 2026",
      "kind": "table",
      "body": "Headcount figures are the publicly disclosed totals at the time of the announcement. Where multiple rounds occurred in a calendar year, the entry reflects the largest single announcement unless otherwise noted. Sources are primary — SEC 8-K, official company blog, or first-party CEO memo — except where only journalist-attributed reporting exists.",
      "tableColumns": [
        "Company",
        "Date",
        "Headcount",
        "Public framing",
        "Label",
        "Primary source"
      ],
      "tableRows": [
        [
          "Google / Alphabet",
          "Jan 20, 2023",
          "~12,000",
          "Pichai memo: hired for a different economic reality; investments in AI continue",
          "AI-adjacent",
          "blog.google CEO memo"
        ],
        [
          "Microsoft",
          "Jan 18, 2023",
          "~10,000",
          "Nadella memo: continued hiring in 'strategic areas including AI'",
          "AI-adjacent",
          "Microsoft 8-K, Nadella memo"
        ],
        [
          "Meta",
          "Mar 14, 2023",
          "~10,000 (plus 11,000 in 2022)",
          "'Year of efficiency'; flatter org; some AI mention but cost-driven",
          "AI-framed",
          "Meta 8-K, Zuckerberg memo"
        ],
        [
          "Amazon",
          "Jan 4, 2023",
          "~18,000 (round 2; ~27,000 cumulative through 2023)",
          "Jassy memo cited cost discipline; AI not the driver",
          "Cost-driven",
          "Amazon corporate blog"
        ],
        [
          "Salesforce",
          "Jan 4, 2023",
          "~8,000 (~10% of workforce)",
          "Benioff letter: hired too many during pandemic; took responsibility",
          "Cost-driven",
          "Salesforce 8-K"
        ],
        [
          "IBM",
          "May 1, 2023 (announced)",
          "~7,800 over multiple years via attrition",
          "Krishna told Bloomberg AI and automation would replace ~30% of back-office roles over five years",
          "AI-driven",
          "Bloomberg interview, Krishna"
        ],
        [
          "Dropbox",
          "Apr 27, 2023",
          "~500 (16%)",
          "Houston memo: 'the AI era of computing has finally arrived'; needed a different skill mix",
          "AI-framed",
          "Dropbox 8-K"
        ],
        [
          "BuzzFeed",
          "Apr 20, 2023",
          "~180 (15%); BuzzFeed News closed",
          "Peretti memo: news unit unprofitable; company pivoting to AI and creators",
          "Cost-driven (separate AI pivot)",
          "Variety, BuzzFeed memo"
        ],
        [
          "CNET (Red Ventures)",
          "Mar 2023",
          "~10% of editorial; ZDNet ~35%",
          "Company stated layoffs unrelated to AI; AI-written content scandal was concurrent",
          "AI-adjacent / disputed",
          "Variety, Futurism reporting"
        ],
        [
          "Klarna",
          "Late 2023 through 2024",
          "~22% headcount reduction via attrition + hiring freeze",
          "Public claim: AI assistant did work of 700 full-time agents",
          "AI-driven (later partially reversed)",
          "Klarna press release, OpenAI case study"
        ],
        [
          "Duolingo",
          "Jan 2024",
          "~10% of contractors (writers and translators)",
          "Duolingo statement: 'no longer need as many people for this work… part of that could be attributed to AI'",
          "AI-driven",
          "CNN, Duolingo statement"
        ],
        [
          "Google / Alphabet",
          "Jan 2024 onward",
          "Multiple rounds, thousands across Ads, Cloud, Pixel, Android",
          "Pichai: 'tough choices' to free capacity for AI investment",
          "AI-adjacent",
          "CBS News, Google internal memos"
        ],
        [
          "Microsoft",
          "2024-2026",
          "Multiple rounds; largest in May 2026 (~6,000+)",
          "Reorganization around AI; concurrent record AI capex",
          "AI-adjacent / partially AI-driven",
          "Microsoft 8-K filings"
        ],
        [
          "Meta",
          "May 2026",
          "~8,000 (additional Reality Labs and other cuts)",
          "Concurrent with ~$145B AI infrastructure spend announcement",
          "AI-adjacent",
          "Meta 8-K, TNW reporting"
        ]
      ]
    },
    {
      "heading": "Timeline: the inflection points",
      "kind": "timeline",
      "body": "Not every event below is a layoff. Some are framing moments — the day a CEO told the public something that changed how subsequent cuts were read.",
      "timelineItems": [
        {
          "date": "Nov 2022",
          "title": "Meta cuts 11,000 (13% of workforce)",
          "body": "Zuckerberg's first major reduction. Pre-dated the AI framing wave. Cited over-hiring during pandemic."
        },
        {
          "date": "Jan 4, 2023",
          "title": "Salesforce announces ~10% cut; Amazon round 2 begins",
          "body": "Benioff and Jassy both lead with over-hiring as the explanation. AI is not invoked as the driver in either case."
        },
        {
          "date": "Jan 18, 2023",
          "title": "Microsoft 10,000",
          "body": "Nadella's memo is the first major one to explicitly say hiring continues 'in strategic areas including AI.' The framing template starts here."
        },
        {
          "date": "Jan 20, 2023",
          "title": "Google 12,000",
          "body": "Pichai's memo names AI as part of the forward investment story without claiming it caused the cut. The AI-adjacent template is now public."
        },
        {
          "date": "Mar 14, 2023",
          "title": "Meta declares 'year of efficiency,' cuts ~10,000 more",
          "body": "Zuckerberg frames flatter organization and operational discipline. AI investment is mentioned in the broader strategy."
        },
        {
          "date": "Apr 27, 2023",
          "title": "Dropbox cuts 500 (16%); Houston memo invokes 'the AI era'",
          "body": "First major US tech layoff where the CEO memo leads with AI as part of the explanation, not just the forward strategy."
        },
        {
          "date": "May 1, 2023",
          "title": "IBM's Krishna tells Bloomberg AI could replace ~7,800 back-office roles over five years",
          "body": "First explicit public commitment by a major US employer to substitute AI for headcount on a named scale."
        },
        {
          "date": "Jan 2024",
          "title": "Duolingo cuts ~10% of contractors",
          "body": "Translators and writers. Company statement is the cleanest direct attribution — the work is being done by AI systems."
        },
        {
          "date": "Feb 2024",
          "title": "Klarna publishes OpenAI case study; claims 700-agent equivalent",
          "body": "Marks the peak of the AI-replaces-headcount narrative cycle. The 700 figure is workload-equivalence, not 700 humans fired."
        },
        {
          "date": "2025",
          "title": "Klarna partially reverses; Amazon refuses the AI framing",
          "body": "Siemiatkowski tells Bloomberg the company is hiring humans again to ensure complex cases get a person. Jassy tells Amazon staff the 2025 cuts are about culture and bureaucracy, not AI or cost — an explicit rejection of the AI-rebranded framing."
        },
        {
          "date": "Jan to May 2026",
          "title": "Tech layoffs surge again; AI framing becomes the dominant rationale",
          "body": "Layoffs.fyi tracks over 100,000 tech job cuts in the first five months of 2026. A larger share of announcements explicitly cite AI substitution than in any prior year."
        }
      ]
    },
    {
      "heading": "Cases worth reading carefully",
      "kind": "cards",
      "body": "These four are the cleanest test cases for what AI-driven layoff language actually means. Each represents a different position on the framing spectrum.",
      "cards": [
        {
          "title": "IBM (AI-driven, on the record)",
          "body": "Arvind Krishna told Bloomberg in May 2023 that he could 'easily see 30% of that getting replaced by AI and automation over a five-year period,' referring to ~26,000 non-customer-facing back-office roles — yielding the widely reported ~7,800 figure. This is the cleanest public commitment in the dataset. The mechanism: attrition plus hiring freeze, not mass firing. Worth tracking whether the five-year horizon (2023 to 2028) actually delivers the substitution at scale.",
          "meta": "~7,800 over five years · attrition mechanism"
        },
        {
          "title": "Klarna (AI-driven, then partially reversed)",
          "body": "The February 2024 OpenAI case study said Klarna's AI assistant handled 2.3 million chats in 30 days, doing the work of 700 full-time agents and projecting ~$40M in 2024 profit improvement. Headcount dropped ~22% via attrition and hiring freeze across 2023-2024. By 2025, CEO Sebastian Siemiatkowski told Bloomberg the company was hiring humans back for complex cases — citing quality complaints and customer dissatisfaction. The cleanest example of AI substitution that worked partially, then hit a quality ceiling.",
          "meta": "22% headcount via attrition · partial reversal 2025"
        },
        {
          "title": "Duolingo (AI-driven, contractor-level)",
          "body": "January 2024 cut ~10% of contractors, primarily translators and writers. Company statement: 'we just no longer need as many people to do the type of work some of these contractors were doing. Part of that could be attributed to AI.' Mechanism: remaining humans review AI-generated translations and acceptable-answer lists. Important because it's contractor headcount (not employees), and the substitution is on a narrow, well-defined task class where transformer output is plausibly good enough.",
          "meta": "~10% of contractors · review-mode workflow"
        },
        {
          "title": "Amazon (AI-rebrand refused)",
          "body": "Andy Jassy's 2025 layoff announcement was notable for what it did NOT say. The CEO told staff explicitly that the cuts were about removing bureaucracy and improving agility — not AI, not cost-cutting. This is the inverse of the AI-rebrand pattern: a major company taking a cost-and-culture cut and deliberately refusing the productivity-story framing that would have played better with investors. Worth contrasting with peers that took the opposite framing choice on cuts of similar shape and size.",
          "meta": "~14,000+ in 2025 round · framing explicitly rejected AI as driver"
        }
      ]
    },
    {
      "heading": "What the framing language actually does",
      "kind": "prose",
      "body": "Companies do not invoke AI in layoff memos by accident. The framing serves three distinct purposes, often simultaneously, and reading them apart helps explain why the same kind of cut can carry very different language.\n\nFirst, it signals to investors that the company is on the productivity side of the AI story. A 10,000-person reduction framed as 'freeing capacity to invest in AI' reads to a market analyst as forward-looking capital reallocation. The same cut framed as 'reducing post-pandemic over-hiring' reads as defensive. Both can be true. The framing choice is a positioning move.\n\nSecond, it provides a strategic narrative for what comes next. A memo that says 'we need a different skill mix' implies the laid-off roles were the wrong roles for the new product — which is partially a real claim about transformer-era engineering needs, and partially a way to tell remaining staff that survival means becoming an AI-fluent contributor. Dropbox's 2023 memo and Google's 2024 memo both lean on this pattern.\n\nThird, it shifts blame from leadership decisions to technological inevitability. 'The AI era has finally arrived' implies that no executive choice could have prevented this restructuring — the technology forced it. This is rarely fully accurate. Most 2023-2024 layoffs were primarily downstream of 2020-2021 over-hiring decisions made by the same executives now describing the cuts as AI-driven. IBM's case is different because the substitution is operationally specified. Dropbox's case is harder to read because the operational mechanism is less specific.\n\nThe practical implication for anyone reading these announcements: the framing tells you what the company wants the cut to mean. It does not tell you what caused it. For causation, read the SEC filing, look at the team affected, and watch what gets hired into the resulting capacity."
    },
    {
      "heading": "Where the data is genuinely uncertain",
      "kind": "callout",
      "body": "Several frequently cited figures in the AI layoff discourse do not survive careful reading. The Klarna '700 agents replaced' number is workload-equivalence — the AI assistant handled volume equivalent to 700 full-time human agents, but Klarna did not lay off 700 named humans to get there; the reduction was via attrition and an avoided hiring ramp. IBM's '7,800 replaced by AI' is a forward-looking ceiling estimate from a Bloomberg interview, with a five-year horizon and an attrition mechanism — not a single-event layoff. Industry aggregate claims like 'X% of all 2025 layoffs were AI-driven' depend heavily on how AI-driven is operationalized; one credible read of layoffs.fyi data suggested under 8% of 2025 announcements explicitly cited AI substitution, with the figure rising sharply through 2026. Numbers above 20% for AI-driven share are common in the press but require careful sourcing — they often conflate AI-framed with AI-driven. When in doubt, prefer SEC filings and CEO memos over secondary aggregation. As of June 2026, no comprehensive academic dataset of AI-driven layoffs has been published that meets economist-grade methodology standards. The best public approximations remain layoffs.fyi (aggregate counts) and journalist-curated lists (framing).",
      "listItems": []
    },
    {
      "heading": "Related AtomEons surfaces",
      "kind": "list",
      "body": "If you are reading this tracker because you are trying to figure out where your own work sits relative to the AI labor signal, these adjacent surfaces may be useful.",
      "listItems": [
        "Learn — the AtomEons skills lane, oriented around durable, transferable craft rather than tool-specific certifications.",
        "Research — the lab notebook for AtomEons' published technical work, including the corpus that informs this tracker.",
        "OrangeBox — the operator's productivity console for solo founders and small teams running on AI-augmented workflows.",
        "B00KMakor — long-form research synthesis from the lab for operators thinking about how to position into a transformed labor market.",
        "VS — head-to-head technical comparisons useful when evaluating which AI providers to consolidate workflow onto.",
        "Tools — small focused utilities maintained by the lab."
      ]
    }
  ],
  "citations": [
    {
      "source": "blog.google/inside-google/message-ceo/january-update/",
      "claim": "Sundar Pichai's January 20, 2023 memo announcing ~12,000 Google layoffs and the AI investment context"
    },
    {
      "source": "cnbc.com — Google to lay off 12,000 people, January 2023",
      "claim": "CNBC verification of the Google 12,000 figure and severance terms"
    },
    {
      "source": "qz.com — Microsoft is cutting 10,000 jobs, January 2023",
      "claim": "Nadella memo announcing ~10,000 Microsoft layoffs and continued AI hiring"
    },
    {
      "source": "Microsoft 8-K filing, January 2023",
      "claim": "SEC disclosure of the 10,000 headcount reduction and Q3 completion target"
    },
    {
      "source": "sec.gov — Meta Platforms 8-K, March 14, 2023",
      "claim": "Meta's ~10,000 March 2023 layoff disclosure and Year of Efficiency framing"
    },
    {
      "source": "fortune.com — Mark Zuckerberg's year of efficiency, March 2023",
      "claim": "Confirmation of Meta's ~10,000 March 2023 cut and hiring freeze on ~5,000 additional roles"
    },
    {
      "source": "sec.gov — Salesforce 8-K letter to employees, January 4, 2023",
      "claim": "Benioff's letter announcing ~10% workforce reduction (~8,000 employees)"
    },
    {
      "source": "wraltechwire.com — IBM looks to turn nearly 8,000 jobs over to AI, May 2023",
      "claim": "Krishna's Bloomberg interview commitment to attrite ~7,800 back-office roles to AI over five years"
    },
    {
      "source": "aljazeera.com — IBM to freeze hiring as CEO expects AI to replace 7,800 jobs, May 2023",
      "claim": "Cross-source verification of the IBM AI substitution figure"
    },
    {
      "source": "techcrunch.com — Dropbox lays off 500 employees, April 2023",
      "claim": "Dropbox 16% cut and Houston's 'era of AI' memo language"
    },
    {
      "source": "sec.gov — Dropbox 8-K filing, April 2023",
      "claim": "SEC disclosure of the 500-employee cut and $37M-$42M associated charges"
    },
    {
      "source": "variety.com — BuzzFeed News shutting down, April 2023",
      "claim": "Peretti memo announcing BuzzFeed News closure and ~180 layoffs (15%)"
    },
    {
      "source": "futurism.com — CNET hits staff with layoffs after AI journalism pivot, 2023",
      "claim": "Reporting on CNET editorial cuts following AI-written article scandal"
    },
    {
      "source": "variety.com — CNET Hit by Layoffs but Says Cuts Unrelated to AI",
      "claim": "CNET official statement disclaiming AI as the cause of the editorial cuts"
    },
    {
      "source": "klarna.com/international/press — Klarna AI assistant handles two-thirds of customer service chats, February 2024",
      "claim": "Klarna's primary-source claim that the AI assistant handled work equivalent to 700 full-time agents"
    },
    {
      "source": "openai.com/index/klarna/",
      "claim": "OpenAI case study documenting the Klarna AI assistant deployment and 700 FTE-equivalence figure"
    },
    {
      "source": "fortune.com — Klarna stopped all hiring to replace workers with AI, December 2024",
      "claim": "Klarna's ~22% headcount reduction via attrition through 2023-2024 ahead of US IPO"
    },
    {
      "source": "entrepreneur.com — Klarna is hiring customer service agents after AI couldn't cut it on calls",
      "claim": "Siemiatkowski's 2025 reversal and reinvestment in human customer service"
    },
    {
      "source": "cnn.com — Duolingo lays off staff as language learning app shifts toward AI, January 2024",
      "claim": "Duolingo's ~10% contractor reduction and partial attribution to AI substitution"
    },
    {
      "source": "cbsnews.com — Google CEO warns of more layoffs in 2024 amid AI push",
      "claim": "Pichai's January 2024 framing of layoffs as freeing capacity for AI investment"
    },
    {
      "source": "layoffs.fyi",
      "claim": "Aggregate tech layoff counts by year used as the structural reference for this tracker"
    },
    {
      "source": "news.crunchbase.com — Tech Layoffs: US Companies With Job Cuts In 2024, 2025 and 2026",
      "claim": "2024 total of ~152,922 tech layoffs across 551 companies per Crunchbase aggregation"
    },
    {
      "source": "geekwire.com — Amazon CEO says massive corporate layoffs were about agility, not AI or cost-cutting, 2025",
      "claim": "Jassy's explicit refusal of the AI-driven framing for Amazon's 2025 reduction"
    },
    {
      "source": "Bloomberg via wraltechwire.com — Krishna interview, May 2023",
      "claim": "Primary mechanism for the IBM AI-substitution number (attrition over five years, ~30% of 26,000 back-office roles)"
    },
    {
      "source": "thenextweb.com — Meta cuts 8,000 jobs amid record revenue, May 2026",
      "claim": "May 2026 Meta layoff of ~8,000 concurrent with large AI infrastructure capex announcement"
    }
  ],
  "crosslinks": [
    {
      "label": "Learn",
      "href": "/learn"
    },
    {
      "label": "Research",
      "href": "/research"
    },
    {
      "label": "OrangeBox",
      "href": "/orangebox"
    },
    {
      "label": "B00KMakor",
      "href": "/b00kmakor"
    },
    {
      "label": "VS comparisons",
      "href": "/vs"
    },
    {
      "label": "Tools",
      "href": "/tools"
    }
  ]
};

const BREADCRUMB = [
  {
    "label": "AtomEons",
    "href": "/"
  },
  {
    "label": "Learn",
    "href": "/learn"
  },
  {
    "label": "layoffs"
  }
];

export const metadata: Metadata = {
  title: "The AI layoffs tracker · AtomEons /learn/layoffs",
  description: "This page tracks corporate layoffs in 2023, 2024, 2025 and into 2026 where the public statement, the CEO memo, or the SEC filing explicitly invoked artificial intelligence as part of the rationale.",
  alternates: { canonical: "https://atomeons.com/learn/layoffs" },
  openGraph: {
    title: "The AI layoffs tracker",
    description: "Corporate workforce cuts framed around AI, 2023 to 2026 best-effort",
    url: "https://atomeons.com/learn/layoffs",
    type: "article",
  },
  robots: { index: true, follow: true },
};

export default function Page() {
  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "The AI layoffs tracker",
    "description": "Corporate workforce cuts framed around AI, 2023 to 2026 best-effort",
    "author": { "@type": "Organization", "name": "AtomEons Systems Laboratory" },
    "publisher": { "@type": "Organization", "name": "AtomEons", "url": "https://atomeons.com" },
    "license": "https://creativecommons.org/licenses/by/4.0/",
    "isAccessibleForFree": true,
    "url": "https://atomeons.com/learn/layoffs",
  };
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} />
      <GenericPage page={PAGE_DATA} breadcrumb={BREADCRUMB} />
    </>
  );
}
