import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "The registry, not the marketplace-of-everything. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /skilski/roadmap · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ skil.ski · roadmap",
    title: "The registry, not the marketplace-of-everything.",
    stamp: "BINDING",
    accent: "pulse",
    rightPrimary: "7",
    rightLabel: "anti-roadmap clauses",
    bottomReceipt: "atomeons.com/skilski/roadmap · CC-BY 4.0",
  });
}
