import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Latent Diffusion · decoded · AtomEons",
  description:
    "Rombach et al. 2022 — the paper that made high-quality AI image generation possible on consumer hardware. Stable Diffusion, Flux, Nano Banana Pro all descend from this. Plain English.",
  alternates: { canonical: "https://atomeons.com/research/decoded/latent-diffusion" },
  robots: { index: true, follow: true },
};

const ACCENT = "#22F0D5";

export default function Page() {
  return (
    <main className="relative z-10 bg-black text-[#F2F4F5]">
      <div className="mx-auto w-full max-w-6xl px-6 pt-6">
        <p className="font-mono text-[11px] tracking-[0.08em] text-[#6B7779]">
          <Link href="/" className="hover:text-[#22F0D5]">AtomEons</Link>{" "}
          <span className="text-[#1A2225]">/</span>{" "}
          <Link href="/research" className="hover:text-[#22F0D5]">Research</Link>{" "}
          <span className="text-[#1A2225]">/</span>{" "}
          <Link href="/research/decoded" className="hover:text-[#22F0D5]">Decoded</Link>{" "}
          <span className="text-[#1A2225]">/</span> Latent Diffusion
        </p>
      </div>

      <section className="border-b border-[#1A2225]">
        <div className="mx-auto w-full max-w-4xl px-6 py-16 md:py-24">
          <p className="font-mono text-[11px] uppercase tracking-[0.22em] text-[#9BA5A7]">
            2022 · arXiv:2112.10752 · Rombach, Blattmann, Lorenz, Esser, Ommer · LMU Munich + Heidelberg + Runway
          </p>
          <h1 className="mt-7 text-balance text-4xl font-medium leading-[1.05] tracking-tight md:text-6xl md:leading-[1]">
            AI art on a{" "}
            <span style={{ color: ACCENT }}>laptop GPU.</span>
          </h1>
          <p className="mt-8 max-w-[62ch] text-[17px] leading-[1.65] text-[#C8CCCE]">
            <span className="text-[#22F0D5]">In one sentence: </span>
            German researchers figured out how to compress the image-generation problem into a 64× smaller mathematical space, making AI image generation tractable on consumer hardware — and launching the open-source generative art era.
          </p>
        </div>
      </section>

      <section className="border-b border-[#1A2225]">
        <div className="mx-auto w-full max-w-4xl px-6 py-16 md:py-24 space-y-12">
          <article>
            <p className="font-mono text-[11px] uppercase tracking-[0.22em]" style={{ color: ACCENT }}>
              01 · Why this matters to your life
            </p>
            <p className="mt-5 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              Every AI image you have seen on the internet since mid-2022 descends from this paper. Stable Diffusion (released August 2022) was the open-source implementation. Flux, the current open-weights state of the art, is a flow-matching extension of the same idea. DALL-E 3, Imagen, Nano Banana Pro — all use the latent-diffusion architecture this paper introduced.
            </p>
            <p className="mt-4 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The atomeons.com hero photography was generated by Nano Banana Pro, which is a member of this family. The reason image generation is cheap enough to do at scale — a few cents per image instead of dollars — is the trick this paper introduced.
            </p>
          </article>

          <article>
            <p className="font-mono text-[11px] uppercase tracking-[0.22em]" style={{ color: ACCENT }}>
              02 · What scientists actually did
            </p>
            <p className="mt-5 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              Diffusion models work by starting with random noise and gradually denoising it into an image. The denoising process is run by a neural network that has been trained to predict what noise should be removed at each step. By 2021 this worked beautifully — Ho et al.&apos;s 2020 DDPM paper was the foundational version — but it was expensive. Each denoising step required running the network at full image resolution. For a 512×512 image, that&apos;s 262,144 pixels processed at every step, for hundreds of steps.
            </p>
            <p className="mt-4 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The Rombach team&apos;s insight: don&apos;t do the diffusion in pixel space. Do it in a much smaller compressed space — a 64×64 latent representation encoded from the original image by a separate neural network called a VAE (Variational Autoencoder). All the heavy denoising work happens in the small space. The final latent is then decoded back to a full-resolution image by the VAE&apos;s decoder.
            </p>
            <p className="mt-4 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The compression ratio is about 48×. That makes everything ~48× cheaper. Suddenly you can train a high-quality model in weeks instead of months, and generate images in seconds on a consumer GPU instead of minutes on a server. The economics flipped from research-lab-only to anyone-can-run-it.
            </p>
            <p className="mt-4 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The other contribution: they showed how to condition the model on text prompts using a pre-trained CLIP text encoder. The result was a model that could take any English description and generate an image matching it. That conditioning is what made the technology consumer-facing.
            </p>
          </article>

          <article>
            <p className="font-mono text-[11px] uppercase tracking-[0.22em]" style={{ color: ACCENT }}>
              03 · What scientists know but rarely say
            </p>
            <p className="mt-5 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The Stability AI release of Stable Diffusion in August 2022 — six months after this paper — was the moment generative art became a real cultural and economic force. The open-weights release meant anyone could run the model. Artists immediately protested that their work had been used as training data without consent. The Getty Images vs. Stability AI lawsuit (filed January 2023, ongoing in 2026) is the high-profile downstream of this paper.
            </p>
            <p className="mt-4 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The technical truth that the paper soft-pedals: latent diffusion is not the ideal mathematical formulation. Subsequent work — particularly flow-matching (Lipman et al. 2022, picked up by Stable Diffusion 3 and Flux) — has produced cleaner objectives. But latent diffusion was good enough to start the era, and most production systems still use variants of the original recipe.
            </p>
            <p className="mt-4 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The thing nobody in image generation likes to say: deeper, persistent failure modes — hands with 6 fingers, faces with uncanny-valley asymmetry, text that says nothing in particular — are baked into how diffusion models reason about images. Each successor model patches some of these but rarely solves them at the level a careful viewer notices. The technology produces stunning images and inscrutable failures from the same architecture.
            </p>
          </article>

          <article>
            <p className="font-mono text-[11px] uppercase tracking-[0.22em]" style={{ color: ACCENT }}>
              04 · What the paper does NOT claim
            </p>
            <p className="mt-5 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The paper does not claim its model is the best image generator. It claims latent diffusion is dramatically more efficient than pixel-space diffusion at comparable quality. The quality bar in the paper was state-of-the-art at the time but has been substantially exceeded by every follow-up model. The paper&apos;s contribution is the architecture, not the absolute output quality.
            </p>
            <p className="mt-4 max-w-[62ch] text-[15px] leading-[1.7] text-[#C8CCCE]">
              The paper also does not address copyright, training-data consent, or the cultural impact of releasing image generation as an open-weights product. Those debates emerged downstream of the Stability AI release. The 2022 paper is a purely technical contribution; the 2022-2026 cultural reckoning is its consequence.
            </p>
          </article>

          <article>
            <p className="font-mono text-[11px] uppercase tracking-[0.22em]" style={{ color: ACCENT }}>
              05 · Read the original
            </p>
            <ul className="mt-5 max-w-[62ch] space-y-3 text-[15px] leading-[1.7] text-[#C8CCCE]">
              <li>· <a href="https://arxiv.org/abs/2112.10752" target="_blank" rel="noopener" className="text-[#22F0D5] underline decoration-[#22F0D5]/40 underline-offset-2 hover:decoration-[#22F0D5]">arxiv.org/abs/2112.10752</a> — the original Latent Diffusion paper.</li>
              <li>· Ho, Jain, Abbeel 2020 (DDPM) — the foundational diffusion-in-pixel-space paper this work builds on. arxiv:2006.11239.</li>
              <li>· Lipman et al. 2022 (Flow Matching) — the cleaner mathematical successor used in Stable Diffusion 3 and Flux. arxiv:2210.02747.</li>
              <li>· Stable Diffusion release notes (August 22, 2022) — the Stability AI launch of the public model.</li>
              <li>· Then see our <Link href="/learn/atlas/diffusion" className="text-[#22F0D5] underline decoration-[#22F0D5]/40 underline-offset-2 hover:decoration-[#22F0D5]">/learn/atlas/diffusion</Link> page for the full 2026 diffusion ecosystem.</li>
            </ul>
          </article>
        </div>
      </section>

      <section className="bg-black">
        <div className="mx-auto w-full max-w-4xl px-6 py-12 text-center">
          <Link href="/research/decoded" className="inline-flex items-center gap-2 rounded-full border border-[#1A2225] px-5 py-2.5 text-sm text-[#9BA5A7] transition-colors hover:text-[#E7EBED]">
            ← decoded index
          </Link>
        </div>
      </section>
    </main>
  );
}
