import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Where the lab connects. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /integrations · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ integrations · stack map",
    title: "Where the lab connects.",
    stamp: "PUBLIC",
    accent: "cyan",
    rightPrimary: "20",
    rightLabel: "services categorized · CC-BY 4.0",
    bottomReceipt: "atomeons.com/integrations · CC-BY 4.0",
  });
}
