import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Where we lose. Where we win. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /orangebox/competitors · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ ORANGEBOX vs alternatives",
    title: "Where we lose. Where we win.",
    stamp: "HONEST",
    accent: "gold",
    rightPrimary: "6",
    rightLabel: "head-to-heads named",
    bottomReceipt: "atomeons.com/orangebox/competitors · CC-BY 4.0",
  });
}
