import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "What the lab costs to run. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /transparency · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ financial transparency · 2026-06",
    title: "What the lab costs to run.",
    stamp: "OPEN BOOK",
    accent: "gold",
    rightPrimary: "$0",
    rightLabel: "VC dollars taken · ever",
    bottomReceipt: "atomeons.com/transparency · CC-BY 4.0",
  });
}
