import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "The inputs to the output. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /influences · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ influences · named",
    title: "The inputs to the output.",
    stamp: "DISCLOSED",
    accent: "cyan",
    rightPrimary: "30",
    rightLabel: "people named · with reasoning",
    bottomReceipt: "atomeons.com/influences · CC-BY 4.0",
  });
}
