import type { MetadataRoute } from "next";
import { PAPERS } from "./_data/research-papers";
import { LESSONS } from "./learn/_data/lessons";
import { PATHS } from "./learn/_data/paths";
import { COMPARISONS } from "./_data/comparisons";

const BASE = "https://atomeons.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const paperEntries: MetadataRoute.Sitemap = PAPERS.map((p) => ({
    url: `${BASE}/research/papers/${p.slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: p.status === "summarized" ? 0.7 : 0.5,
  }));

  const lessonEntries: MetadataRoute.Sitemap = LESSONS.map((l) => ({
    url: `${BASE}/learn/lesson/${l.slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.85,
  }));

  const pathEntries: MetadataRoute.Sitemap = PATHS.map((p) => ({
    url: `${BASE}/learn/${p.id}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.9,
  }));

  return [
    { url: `${BASE}/`, lastModified: now, changeFrequency: "weekly", priority: 1.0 },
    { url: `${BASE}/learn`, lastModified: now, changeFrequency: "weekly", priority: 0.99 },
    { url: `${BASE}/learn/where-am-i`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/learn/library`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/learn/playbooks`, lastModified: now, changeFrequency: "weekly", priority: 0.95 },
    { url: `${BASE}/learn/decision-tree`, lastModified: now, changeFrequency: "weekly", priority: 0.94 },
    { url: `${BASE}/learn/cheatsheet`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/mistakes`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cases`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/quiz`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/prompts`, lastModified: now, changeFrequency: "daily", priority: 0.92 },
    { url: `${BASE}/learn/resources`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/learn/faq`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/templates`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/healthcare-ai`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/legal-ai`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/marketing-ai`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/education-ai`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/finance-ai`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/cheatsheet/es`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/learn/cheatsheet/fr`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/learn/cheatsheet/pt`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/learn/cheatsheet/hi`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/learn/cheatsheet/zh`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/learn/cheatsheet/ar`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/learn/videos`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/synthesis`, lastModified: now, changeFrequency: "weekly", priority: 0.94 },
    { url: `${BASE}/learn/deep`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/cyber`, lastModified: now, changeFrequency: "weekly", priority: 0.94 },
    { url: `${BASE}/learn/cyber/path`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/labs`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/hackerone`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/legal`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/serve`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/certs`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/ai-security`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/cyber/cyberwar`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/cyber/modern`, lastModified: now, changeFrequency: "daily", priority: 0.95 },
    { url: `${BASE}/learn/cyber/llm-warfare`, lastModified: now, changeFrequency: "daily", priority: 0.95 },
    { url: `${BASE}/learn/cyber/platforms`, lastModified: now, changeFrequency: "weekly", priority: 0.94 },
    { url: `${BASE}/learn/cyber/breaches`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/cyber/threat-actors`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/cyber/tools`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/heroes`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/cyber/timeline`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/cyber/books`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/cyber/employers`, lastModified: now, changeFrequency: "weekly", priority: 0.94 },
    { url: `${BASE}/learn/cyber/doctrine`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/karp`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/cyber/luckey`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/cyber/contracts`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/cyber/programs`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/learn/cyber/start`, lastModified: now, changeFrequency: "weekly", priority: 0.96 },
    { url: `${BASE}/learn/cyber/ot-ics`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/cyber/mobile-security`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/cyber/iot-embedded`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/cyber/open-source`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/cyber/conferences`, lastModified: now, changeFrequency: "weekly", priority: 0.90 },
    // nvidia-tier-50 sub-area index pages
    { url: `${BASE}/learn/atlas`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/career`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/learn/trust`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/decode`, lastModified: now, changeFrequency: "weekly", priority: 0.90 },
    { url: `${BASE}/learn/calc`, lastModified: now, changeFrequency: "weekly", priority: 0.94 },
    // nvidia-tier-50: 38 content pages + 12 calculators (wf_c1eaafe8-714)
    { url: `${BASE}/learn/models`, lastModified: now, changeFrequency: "weekly", priority: 0.95 },
    { url: `${BASE}/learn/inference-providers`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/leaderboard`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/open-weights`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/learn/news`, lastModified: now, changeFrequency: "daily", priority: 0.93 },
    { url: `${BASE}/learn/funding`, lastModified: now, changeFrequency: "weekly", priority: 0.90 },
    { url: `${BASE}/learn/regulation`, lastModified: now, changeFrequency: "weekly", priority: 0.91 },
    { url: `${BASE}/learn/failures`, lastModified: now, changeFrequency: "weekly", priority: 0.90 },
    { url: `${BASE}/learn/layoffs`, lastModified: now, changeFrequency: "weekly", priority: 0.88 },
    { url: `${BASE}/learn/conferences`, lastModified: now, changeFrequency: "weekly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/history`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/transformer-variants`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/rlhf-family`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/mech-interp`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/multimodal`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/embeddings`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/hallucinations`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/safety`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/moe`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/context`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/training`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/post-training`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/atlas/agents`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/learn/atlas/scaling-laws`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/benchmarks`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/learn/atlas/rag`, lastModified: now, changeFrequency: "monthly", priority: 0.93 },
    { url: `${BASE}/learn/atlas/quantization`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/inference`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/reasoning`, lastModified: now, changeFrequency: "monthly", priority: 0.93 },
    { url: `${BASE}/learn/atlas/diffusion`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/cyber/youtube`, lastModified: now, changeFrequency: "weekly", priority: 0.89 },
    { url: `${BASE}/learn/cyber/podcasts`, lastModified: now, changeFrequency: "weekly", priority: 0.89 },
    { url: `${BASE}/learn/career/pathways`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/career/skill-tree`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/career/salaries`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/learn/career/resume`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/career/interviews`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/career/non-technical`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/career/negotiation`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/career/independent`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/trust/threat-model`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/trust/prompt-injection`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/trust/data-residency`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/trust/compliance`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/decode/acronyms`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${BASE}/learn/decode/papers`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${BASE}/learn/decode/people`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${BASE}/learn/decode/jargon`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${BASE}/learn/calc/tools/cost-calculator`, lastModified: now, changeFrequency: "monthly", priority: 0.93 },
    { url: `${BASE}/learn/calc/tools/token-counter`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/calc/tools/model-comparator`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/learn/calc/tools/stack-recommender`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/calc/tools/hardware-calculator`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/calc/tools/break-even`, lastModified: now, changeFrequency: "monthly", priority: 0.89 },
    { url: `${BASE}/learn/calc/tools/prompt-diff`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/calc/tools/roi`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/calc/tools/redact`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/calc/tools/jailbreak-checker`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/learn/calc/tools/context-fit`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${BASE}/learn/calc/tools/carbon`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${BASE}/research/lessons-from-sci-fi/chapters`, lastModified: now, changeFrequency: "weekly", priority: 0.86 },
    { url: `${BASE}/research/lessons-from-sci-fi/tng`, lastModified: now, changeFrequency: "weekly", priority: 0.86 },
    { url: `${BASE}/prompt-kit`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/glossary`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/tools`, lastModified: now, changeFrequency: "weekly", priority: 0.94 },
    { url: `${BASE}/vs`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    ...COMPARISONS.map((c) => ({
      url: `${BASE}/vs/${c.slug}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.83,
    })),
    ...pathEntries,
    ...lessonEntries,
    { url: `${BASE}/ai`, lastModified: now, changeFrequency: "weekly", priority: 0.97 },
    { url: `${BASE}/search`, lastModified: now, changeFrequency: "monthly", priority: 0.4 },
    { url: `${BASE}/start`, lastModified: now, changeFrequency: "weekly", priority: 0.95 },
    { url: `${BASE}/orangebox`, lastModified: now, changeFrequency: "weekly", priority: 0.95 },
    { url: `${BASE}/orangebox-primer`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/skilski`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/b00kmakor`, lastModified: now, changeFrequency: "daily", priority: 0.94 },
    { url: `${BASE}/i-am-ai`, lastModified: now, changeFrequency: "weekly", priority: 0.95 },
    { url: `${BASE}/i-am-ai/sample`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/supermodels`, lastModified: now, changeFrequency: "weekly", priority: 0.95 },
    { url: `${BASE}/books`, lastModified: now, changeFrequency: "weekly", priority: 0.92 },
    { url: `${BASE}/receipts`, lastModified: now, changeFrequency: "weekly", priority: 0.88 },
    { url: `${BASE}/legal`, lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE}/press`, lastModified: now, changeFrequency: "weekly", priority: 0.85 },
    { url: `${BASE}/account`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE}/founders-view`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${BASE}/research/about`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/research/papers`, lastModified: now, changeFrequency: "weekly", priority: 0.85 },
    { url: `${BASE}/research/lessons-from-sci-fi`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/research/lessons-from-sci-fi/monograph`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/research/decoded`, lastModified: now, changeFrequency: "weekly", priority: 0.93 },
    { url: `${BASE}/research/decoded/attention-is-all-you-need`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/scaling-laws`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/chain-of-thought`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/constitutional-ai`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/sparse-autoencoders`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/alexnet`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/gpt-3`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/rlhf`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/latent-diffusion`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/alphafold`, lastModified: now, changeFrequency: "monthly", priority: 0.93 },
    { url: `${BASE}/research/decoded/bert`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/word2vec`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/resnet`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/gans`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/alphago`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/alphazero`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/rag`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/mamba`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/dpo`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/mixture-of-experts`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/sleep-immune`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/research/decoded/polygenic-risk-scores`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/fasting-autophagy`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/compound-interest-saving`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/research/decoded/exercise-mortality`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/evals`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/world-models`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/synthetic-data`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/fine-tuning`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/prompt-engineering`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/learn/atlas/mlops`, lastModified: now, changeFrequency: "monthly", priority: 0.91 },
    { url: `${BASE}/intel/x-algorithm`, lastModified: now, changeFrequency: "weekly", priority: 0.85 },
    ...paperEntries,
    { url: `${BASE}/pricing`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/support`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/changelog`, lastModified: now, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE}/now`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/faq`, lastModified: now, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE}/about`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/manifesto`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/design-system`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${BASE}/legal/terms`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE}/legal/privacy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE}/legal/refund`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE}/legal/pricing`, lastModified: now, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE}/dynamic-world-pricing`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
  ];
}
