import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Ship the artifact, learn the lesson. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /learn/projects · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ projects · build-along",
    title: "Ship the artifact, learn the lesson.",
    stamp: "BUILD",
    accent: "cyan",
    rightPrimary: "7",
    rightLabel: "projects · upper 4 levels",
    bottomReceipt: "atomeons.com/learn/projects · CC-BY 4.0",
  });
}
