import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Stop reading. Start doing. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /learn/labs · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ labs · hands-on",
    title: "Stop reading. Start doing.",
    stamp: "HANDS-ON",
    accent: "cyan",
    rightPrimary: "12",
    rightLabel: "labs · 5-level coverage",
    bottomReceipt: "atomeons.com/learn/labs · CC-BY 4.0",
  });
}
