import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Every choice is deliberate. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /aesthetic · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ visual language · V3 noir",
    title: "Every choice is deliberate.",
    stamp: "MANIFESTO",
    accent: "cyan",
    rightPrimary: "11",
    rightLabel: "color palette · 10 authoring rules",
    bottomReceipt: "atomeons.com/aesthetic · CC-BY 4.0",
  });
}
