import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "No mystery boxes. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /colophon · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ colophon · stack inventory",
    title: "No mystery boxes.",
    stamp: "OPEN STACK",
    accent: "cyan",
    rightPrimary: "16",
    rightLabel: "deps pinned · 9 explicit no-uses",
    bottomReceipt: "atomeons.com/colophon · CC-BY 4.0",
  });
}
