import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Active Directory Defense Doctrine · AtomEons Cyber",
  description: "Tier 0 protection, BloodHound for blue team, Kerberoasting + Golden Ticket awareness, ESC vulnerabilities, the post-2024 AD-defense playbook. Public defense doctrine only.",
  alternates: { canonical: "https://atomeons.com/learn/cyber/active-directory-defense" },
  openGraph: { title: "Active Directory Defense · AtomEons", description: "Defense doctrine, public-info only. Tier 0, BloodHound BT, Microsoft Defender for Identity.", url: "https://atomeons.com/learn/cyber/active-directory-defense", type: "article" },
};

export default function Page() {
  return (
    <main className="bg-[#08090B] text-[#F4F4F2] antialiased">
      <section className="border-b border-[#1F242B]"><div className="mx-auto max-w-4xl px-6 pt-20 pb-12 md:px-10 md:pt-28 md:pb-20">
        <p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#7a818a]"><Link href="/learn/cyber" className="hover:text-[#22F0D5]">§ Cyber</Link><span className="mx-3 text-[#1F242B]">·</span><span className="text-[#22F0D5]">Identity · enterprise defense</span></p>
        <h1 className="mt-8 max-w-[24ch] text-balance text-[clamp(36px,6vw,72px)] font-extralight leading-[1.04] tracking-[-0.025em] text-[#F4F4F2]">Active Directory — defense doctrine</h1>
        <p className="mt-8 max-w-[64ch] font-serif text-[19px] leading-[1.55] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Most enterprise compromise still passes through Active Directory. The defensive doctrine has matured around tiered administration, identity monitoring, and graph-based attack-path analysis — the same tooling red teams use, run by the blue team first.</p>
      </div></section>

      <article className="mx-auto max-w-3xl px-6 py-16 md:px-10 md:py-24 space-y-12">
        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What it is</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Active Directory Domain Services (AD DS) is Microsoft&apos;s on-prem identity and access management directory, deployed in nearly every enterprise above 100 users. Its design from 2000 prioritized convenience over least-privilege; every major nation-state intrusion campaign of the last decade leveraged AD weaknesses for privilege escalation and lateral movement. Defense doctrine since 2015 — Microsoft&apos;s tier model, BloodHound for the blue team, Microsoft Defender for Identity — exists to retrofit modern security onto a 25-year-old design.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>How it actually works</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}><em>Tier model</em> (Microsoft, 2014, formalized in the &quot;privileged access workstation&quot; doctrine) partitions privileged accounts into three tiers. Tier 0: Domain Controllers, AD CS, federation services, and any account that can compromise these. Tier 1: enterprise servers running business-critical applications. Tier 2: end-user workstations. Credentials at each tier may only authenticate to that tier&apos;s assets. A Tier 0 admin never logs in to a workstation; a workstation account never has a domain admin token. The mitigation is for the well-documented Pass-the-Hash / Pass-the-Ticket lateral movement classes.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}><em>BloodHound</em> (SpecterOps, originally a red-team tool released DEF CON 24 in 2016) builds a directed graph of every principal, group, ACL, GPO, and session relationship in AD. The graph reveals attack paths — chains of permission misuses that let an attacker pivot from a low-privilege foothold to Domain Admin. Blue teams use BloodHound Community Edition (BHCE, 2024) or BloodHound Enterprise to find and close those paths before the red team finds them. The 2023-2025 generation handles Azure AD / Entra ID alongside on-prem AD.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}><em>AD CS ESC vulnerabilities</em> (Will Schroeder + Lee Christensen, SpecterOps, 2021) — the &quot;Certified Pre-Owned&quot; whitepaper — catalogued certificate-template misconfigurations that allow privilege escalation through Active Directory Certificate Services. Eight ESC techniques (ESC1-ESC8) became the standard audit checklist. Microsoft followed up with the May 2022 KB5014754 advisory and CVE-2022-26923 patch.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}><em>Detection</em> centers on identity-aware monitoring. Microsoft Defender for Identity (formerly Azure Advanced Threat Protection / ATA) ingests domain-controller traffic and authentication telemetry to surface anomalies: Kerberoasting attempts (TGS requests for service accounts with weak passwords), DCSync activity (replication requests from non-DC accounts), Golden Ticket forgery indicators, lateral movement patterns. CrowdStrike Falcon Identity Protection and Semperis cover the same surface from EDR + dedicated AD-monitoring angles.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Receipts</h2><ol className="space-y-4 font-serif text-[17px] leading-[1.6] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Microsoft. <em>Securing Privileged Access Reference Material</em> — the tier model documentation. <span className="font-mono text-[12px] text-[#7a818a]">aka.ms/SPA</span></li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Robbins, Vazarkar, Schroeder. <em>BloodHound: Six Degrees of Domain Admin</em>, DEF CON 24, 2016.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Schroeder, Christensen. <em>Certified Pre-Owned: Abusing Active Directory Certificate Services</em>, SpecterOps whitepaper, June 2021. The ESC1-ESC8 taxonomy.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">CVE-2022-26923, <em>Active Directory Domain Services Elevation of Privilege Vulnerability</em>, CVSS 8.8 — Microsoft May 2022 patch.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Microsoft Defender for Identity documentation, <span className="font-mono text-[12px] text-[#7a818a]">learn.microsoft.com/defender-for-identity</span>.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">MITRE ATT&amp;CK T1558 (Steal or Forge Kerberos Tickets), T1003.006 (DCSync), T1207 (Rogue Domain Controller) — the AD-specific techniques.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">CISA Joint Advisory AA22-279A (October 2022), <em>Top CVEs Actively Exploited by People&apos;s Republic of China State-Sponsored Cyber Actors</em> — heavy AD focus.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">BloodHound Community Edition repo, <span className="font-mono text-[12px] text-[#7a818a]">github.com/SpecterOps/BloodHound</span>.</li>
        </ol></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What practitioners do with it</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The 2026 baseline: run BloodHound regularly against your domain. Patch every ESC. Enforce tier separation with privileged access workstations + just-in-time admin access. Deploy Defender for Identity or equivalent. Disable NTLM where possible; enforce Kerberos with AES encryption only; require strong service-account passwords or convert to gMSAs. Migrate to Microsoft Entra ID (Azure AD) for new applications; reduce on-prem AD&apos;s attack surface over time.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What it is NOT</h2><ul className="space-y-4 font-serif text-[17px] leading-[1.6] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not solved by cloud migration.</strong> Entra ID inherits some of AD&apos;s privilege models. Token-theft, consent-phishing, and federation attacks replace Pass-the-Hash. Different attack surface, same defense discipline.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not a one-time audit.</strong> AD permissions drift continuously as people change roles. Quarterly BloodHound runs + automated detection is the minimum.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not red-team-only tooling.</strong> BloodHound was built for red teams but is most valuable to blue teams who run it on their own domain first.</li>
        </ul></section>

        <div className="border-t border-[#1F242B] pt-12"><Link href="/learn/cyber" className="border border-[#1F242B] bg-[#0F1114] px-5 py-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[#F4F4F2] hover:border-[#22F0D5] hover:text-[#22F0D5]">← Back to Cyber</Link></div>
      </article>
    </main>
  );
}
