import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Different instruments for different stages. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /b00kmakor/competitors · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ B00KMAKR vs alternatives",
    title: "Different instruments for different stages.",
    stamp: "HONEST",
    accent: "gold",
    rightPrimary: "5",
    rightLabel: "head-to-heads named",
    bottomReceipt: "atomeons.com/b00kmakor/competitors · CC-BY 4.0",
  });
}
