import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "How we made the curriculum. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /teach · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ teach · methodology",
    title: "How we made the curriculum.",
    stamp: "CC-BY 4.0",
    accent: "cyan",
    rightPrimary: "8",
    rightLabel: "principles · open source",
    bottomReceipt: "atomeons.com/teach · CC-BY 4.0",
  });
}
