/**
 * /v3 — preview of the trillion-dollar redesign (noir-cinema winner).
 *
 * Imports the page.v3.tsx composition so operator can compare against /
 * (current homepage) without overwriting it. If V3 wins the side-by-side,
 * promote by renaming or by replacing app/page.tsx contents.
 *
 * Generated by trillion v2 workflow wf_4708660f-bb7, applied 2026-06-02.
 */

export { default } from "../page.v3";

export const metadata = {
  title: "V3 preview · noir-cinema · AtomEons",
  description:
    "Preview the trillion-dollar redesign on a non-production route. Compare to / before promoting.",
  alternates: { canonical: "https://atomeons.com/v3" },
  robots: { index: false, follow: false },
};
