import type { Metadata } from "next";
import { GenericPage } from "@/app/_components/generic-page/GenericPage";
import type { ContentPage } from "@/app/_components/generic-page/types";

// Auto-materialized from wf_c1eaafe8-714 (nvidia-tier-50 workflow).
// Generated by .scripts/materialize-nvidia-tier-50.mjs.

const PAGE_DATA: ContentPage = {
  "slug": "regulation",
  "title": "AI regulation tracker by jurisdiction",
  "subtitle": "What's in force, what's pending, what's posture — as of June 2026",
  "accent": "#22F0D5",
  "intro": "AI law moved from white papers to enforceable statute between 2023 and 2026. The center of gravity now sits in three places: Brussels, where the EU AI Act became the world's first horizontal AI statute and entered phased application starting February 2025; Washington and Sacramento, where federal posture flipped twice within thirteen months and California passed the first US state-level frontier AI law; and Beijing, where China has been quietly regulating generative AI by administrative measure since August 2023. Everywhere else — UK, Canada, Brazil, India, Japan — is somewhere on the spectrum between voluntary frameworks and stalled comprehensive bills.\n\nThis page is a snapshot, not a legal opinion. Regulation is moving on a roughly six-month half-life right now: Colorado's flagship AI act was passed, postponed, then largely replaced inside eighteen months. The Trump administration's December 2025 executive order on preemption is being litigated. The EU's GPAI Code of Practice took ten months from publication to first enforcement window. If a fact below is older than the date stamp at the bottom of each row, verify with the primary source we cite before relying on it.\n\nWe tried to keep marketing-speak out and citations in. Every figure that matters — fine ceiling, effective date, compute threshold — is linked to a government page, an official text, or a law firm summary from a firm that has to be right because their clients are paying them to be right. Where we say \"as of June 2026 best-effort,\" it means we checked the source the week of publication and the rule could still slip.\n\nIf you are shipping a model, deploying an automated decision tool, or writing policy yourself, treat this as a map of the terrain, not the legal advice. The terrain is unstable on purpose — regulators want it that way while they figure out where the harms actually land.",
  "sections": [
    {
      "heading": "What's in force right now",
      "kind": "callout",
      "body": "As of June 2026, the binding regimes you can actually be fined under are: the EU AI Act's prohibited-practices and AI-literacy obligations (live since February 2 2025), the EU AI Act's general-purpose AI model obligations (live since August 2 2025, first enforcement window August 2 2026), China's Interim Measures for Generative AI Services (live since August 15 2023), NYC Local Law 144 on automated employment decision tools (live since July 5 2023), California AB 2013's training-data transparency disclosures (live since January 1 2026), California SB 53's frontier-model transparency obligations (signed September 29 2025, effective January 1 2026), and Japan's AI Promotion Act (most provisions effective June 4 2025 — but with no monetary penalties). Everything else on this page is either pending, postponed, voluntary, or under active litigation."
    },
    {
      "heading": "The major regimes at a glance",
      "kind": "table",
      "body": "One row per jurisdiction. \"Status\" is what's actually binding today, not what was announced. Maximum fine is the headline ceiling — most enforcement will land well below it.",
      "tableColumns": [
        "Jurisdiction",
        "Instrument",
        "Status (Jun 2026)",
        "Risk model",
        "Max fine"
      ],
      "tableRows": [
        [
          "EU",
          "AI Act (Reg 2024/1689)",
          "Phased in force",
          "Risk-tiered (prohibited / high / limited / minimal)",
          "€35M or 7% global turnover"
        ],
        [
          "US federal",
          "EO 14179 + Dec 2025 EO + AI Action Plan",
          "Deregulatory posture; preempting state laws",
          "None — innovation-first",
          "n/a"
        ],
        [
          "California",
          "SB 53 (frontier) + AB 2013 (training data)",
          "In force Jan 1 2026",
          "Compute-threshold + transparency",
          "$1M per violation (SB 53)"
        ],
        [
          "Colorado",
          "SB 24-205 → SB 26-189",
          "Original act replaced; June 30 2026 effective date",
          "High-risk + notice/transparency",
          "AG-enforced civil penalties"
        ],
        [
          "UK",
          "Voluntary + AI Security Institute",
          "No comprehensive statute",
          "Sector regulators + voluntary code",
          "n/a"
        ],
        [
          "China",
          "Interim Measures for Generative AI (CAC)",
          "In force Aug 15 2023",
          "Filing + security review for public-opinion services",
          "Existing cyber/data laws"
        ],
        [
          "Brazil",
          "PL 2338/2023",
          "Senate-passed; Chamber under review",
          "Risk-tiered (EU-like)",
          "Pending"
        ],
        [
          "Canada",
          "AIDA (Bill C-27)",
          "Dead — Parliament prorogued Jan 2025",
          "n/a (would have been risk-tiered)",
          "n/a"
        ],
        [
          "India",
          "IT Rules 2026 Amendment + DPDP Act",
          "AI-content labeling effective Feb 20 2026",
          "No standalone AI law",
          "Existing IT Act penalties"
        ],
        [
          "Japan",
          "AI Promotion Act 2025",
          "Most provisions live Jun 4 2025",
          "Innovation-first; no risk classification",
          "No monetary penalties"
        ]
      ]
    },
    {
      "heading": "European Union — the only horizontal statute that's actually live",
      "kind": "prose",
      "body": "The EU AI Act entered into force on August 1 2024 and applies in phases. Article 5's prohibited practices — government social scoring, untargeted facial-image scraping, emotion recognition in workplaces and schools, real-time remote biometric ID in public spaces (narrow law-enforcement carve-outs), exploitative manipulation of vulnerable groups — became enforceable on February 2 2025, along with AI literacy obligations for deployers. General-purpose AI model obligations took effect August 2 2025, covering transparency, copyright policy, and systemic-risk assessment for models above the 10^25 FLOP compute threshold. High-risk system obligations and Article 50 transparency rules apply from August 2 2026. The full Act applies by August 2 2026 with limited grandfathering through 2027.\n\nScope is broad: the Act applies to providers placing AI systems on the EU market and to deployers in the EU, regardless of where the provider is established. A US-based foundation model offered to EU users is in scope. Penalties under Article 99 ladder from €7.5M or 1% of global turnover (false information) to €15M or 3% (high-risk obligations) to €35M or 7% (prohibited practices) — whichever is higher, with reciprocal SME caps using whichever is lower. The Commission has emphasized that enforcement actions against GPAI providers won't begin until August 2 2026, giving a one-year onboarding window.\n\nThe voluntary GPAI Code of Practice, finalized July 10 2025, gives providers a presumption-of-compliance route on Transparency, Copyright, and (for systemic-risk models) Safety and Security. Most major frontier labs signed at least the first two chapters; xAI signed only Safety and Security, meaning it has to demonstrate transparency and copyright compliance via alternative means."
    },
    {
      "heading": "United States — federal posture flipped twice",
      "kind": "timeline",
      "body": "Federal AI policy in the US shifted from Biden-era risk management to Trump-era deregulation between October 2023 and December 2025. Three documents matter.",
      "timelineItems": [
        {
          "date": "Oct 30 2023",
          "title": "Executive Order 14110 (Biden)",
          "body": "Required developers of dual-use foundation models above 10^26 FLOPs to report safety test results to the Commerce Department under the Defense Production Act. Directed NIST to develop AI safety standards. Set out civil-liberties, equity, and national-security priorities for federal agency AI use."
        },
        {
          "date": "Jan 20 2025",
          "title": "EO 14148 rescinds EO 14110 (Trump)",
          "body": "Within hours of taking office, Trump revoked EO 14110 along with dozens of other Biden executive actions. The safety reporting requirements for frontier model training runs ended."
        },
        {
          "date": "Jan 23 2025",
          "title": "EO 14179: Removing Barriers to American Leadership in AI",
          "body": "Replacement order. Directs agencies to revise or rescind policies that act as barriers to AI development. Frames US AI leadership as the federal priority. No safety reporting mandate, no civil-rights specific obligations."
        },
        {
          "date": "Jul 2025",
          "title": "America's AI Action Plan",
          "body": "Policy roadmap from the White House emphasizing AI \"dominance,\" deregulation, and warnings against state-level regulatory \"fragmentation.\" Sets up the rationale for the December 2025 preemption order."
        },
        {
          "date": "Dec 11 2025",
          "title": "EO on National Policy Framework for AI",
          "body": "Establishes an AI Litigation Task Force to challenge state AI laws in court, threatens federal funding to states with \"onerous\" AI rules, and directs the FCC to consider a federal AI reporting standard that would preempt state law. Carve-outs preserve state authority over child safety, data center permitting, and state government procurement. Currently being challenged on constitutional grounds."
        }
      ]
    },
    {
      "heading": "US states — the laboratory California won",
      "kind": "cards",
      "body": "With no federal statute, state legislatures filled the gap between 2023 and 2025. California passed two laws that matter for frontier model and generative AI developers. Colorado tried to pass the most ambitious state AI act in the country, then walked most of it back. NYC ran the first algorithmic-bias audit regime. Texas, Utah, Tennessee, Illinois, and others have narrower laws on specific harms.",
      "cards": [
        {
          "title": "California SB 53 — Transparency in Frontier AI Act",
          "body": "Signed by Newsom September 29 2025. First US state law specifically targeting frontier model developers. Applies to models trained with more than 10^26 computational operations and to \"large frontier developers\" with over $500M in annual revenue. Requires published governance frameworks, transparency reports, critical-safety-incident reporting (15-day window), and whistleblower protections. Penalties capped at $1M per violation.",
          "meta": "Effective: January 1 2026"
        },
        {
          "title": "California AB 2013 — Training Data Transparency",
          "body": "Signed September 28 2024, effective January 1 2026. Requires developers of generative AI systems made publicly available to Californians to publish high-level summaries of training datasets used for models released or substantially modified on or after January 1 2022. Twelve enumerated disclosure categories including data sources, copyright status, and personal-information presence. Enforced through the Unfair Competition Law. xAI lost its preliminary-injunction challenge March 4 2026.",
          "meta": "Effective: January 1 2026"
        },
        {
          "title": "California SB 1047 — vetoed",
          "body": "Would have required safety evaluations and a \"kill switch\" for models costing over $100M to train and using more than 10^26 FLOPs. Anthropic, the Center for AI Safety, and Elon Musk supported it; Meta, OpenAI, and Speaker Pelosi opposed. Vetoed by Newsom September 29 2024 — his stated concern was that compute-only thresholds miss small-but-risky models. SB 53 is the successor.",
          "meta": "Status: Vetoed Sep 29 2024"
        },
        {
          "title": "Colorado SB 24-205 — replaced",
          "body": "Originally the most ambitious US state AI law: risk management programs, annual impact assessments, algorithmic-discrimination duties for deployers of high-risk AI in employment, housing, credit, education, healthcare. Effective date pushed from February 2026 to June 2026. Then replaced by SB 26-189 in May 2026, which dropped most of the substantive obligations in favor of notice-and-transparency. AG-enforced.",
          "meta": "Replacement effective: June 30 2026"
        },
        {
          "title": "NYC Local Law 144 — Automated Employment Decision Tools",
          "body": "Effective January 1 2023, enforcement began July 5 2023. Employers and employment agencies using AEDTs to substantially screen candidates must commission an annual independent bias audit, publish results, and notify candidates. Civil penalties $500–$1,500 per day. December 2025 NY State Comptroller audit found enforcement by DCWP has been weak; complaint-based and under-resourced.",
          "meta": "Live since: Jul 5 2023"
        }
      ]
    },
    {
      "heading": "China — first to regulate generative AI, quietly",
      "kind": "prose",
      "body": "China's Interim Measures for the Management of Generative AI Services took effect August 15 2023, issued jointly by the Cyberspace Administration of China (CAC) and six other agencies. They cover any generative AI service offered to the Chinese public — text, image, audio, video, code — but with a critical scoping qualifier: only services with \"public opinion attributes or social mobilization capabilities\" trigger the heavier Article 17 obligations of security assessment by the CAC and algorithm filing within 10 business days of launch.\n\nThe Measures require providers to ensure training data legality, label AI-generated content, prevent illegal content generation, and protect personal information. The final version softened from the draft: the CAC adopted what it described as an \"inclusive and prudent\" approach and emphasized classified-and-graded supervision rather than blanket rules. Penalties are not bespoke — violations are sanctioned under existing instruments including the Cybersecurity Law, Data Security Law, Personal Information Protection Law, and the Law on Scientific and Technological Progress.\n\nIn practice, China runs the deepest existing operational regime for generative AI consumer services. Major Chinese model providers (Baidu, Alibaba, ByteDance, Moonshot, DeepSeek and others) have filed algorithms and obtained CAC clearance. For non-Chinese providers, the practical reach is limited because most Western models are not legally accessible inside the PRC."
    },
    {
      "heading": "UK — voluntary, sectoral, security-pivoted",
      "kind": "prose",
      "body": "The UK has no comprehensive AI statute. Instead it leans on existing sector regulators (CMA, ICO, FCA, MHRA, Ofcom) interpreting AI use under their existing remits, supported by voluntary standards and a government AI white-paper framework first published in March 2023.\n\nThe most concrete UK institution is the AI Safety Institute, founded around the November 2023 Bletchley Park summit and renamed the AI Security Institute on February 14 2025 by Technology Secretary Peter Kyle. The rebrand signaled a narrower remit: model misuse for cyberattacks, biological and chemical weapons, and other national-security risks — explicitly de-emphasizing algorithmic bias and free-speech concerns. Engagement with the Institute's pre-deployment evaluation program is voluntary for frontier developers, though most major Western labs participate.\n\nAs of June 2026 best-effort, the Labour government has consulted on a binding AI bill targeting the most powerful frontier models but has not introduced one. The UK position remains: existing regulators plus voluntary cooperation, with a security-tilted national institute, and a watchful eye on the EU AI Act's effect on transatlantic deployment."
    },
    {
      "heading": "Asia and the Americas beyond the headline three",
      "kind": "table",
      "body": "Brazil, Canada, India, and Japan are the four other jurisdictions worth tracking. They span the full range from \"comprehensive bill almost passed\" to \"law in force but no penalties\" to \"comprehensive bill collapsed in the legislature.\"",
      "tableColumns": [
        "Country",
        "Instrument",
        "Where it actually is",
        "What it actually does"
      ],
      "tableRows": [
        [
          "Brazil",
          "PL 2338/2023",
          "Senate approved Dec 10 2024; Chamber of Deputies special committee formed Apr 4 2025; no vote date set",
          "EU-style risk tiers (excessive / high / non-high). ANPD likely to be central authority. Watch for amendments in 2026."
        ],
        [
          "Canada",
          "Bill C-27 / AIDA",
          "Dead. Parliament prorogued Jan 6 2025, bill died on the order paper. Trudeau resigned; April 2025 election",
          "Canada now has no federal AI statute. Operating on PIPEDA (2000). Future AI bill will likely be decoupled from privacy reform."
        ],
        [
          "India",
          "IT Rules 2026 Amendment + DPDP Act",
          "Amendment notified Feb 10 2026, effective Feb 20 2026. India AI Governance Guidelines published Nov 2025 — non-binding",
          "Synthetically generated information (deepfakes, AI text/audio/image/video) must carry continuous, clearly-visible labels. Intermediary due-diligence obligations expanded. No standalone AI law in sight."
        ],
        [
          "Japan",
          "AI Promotion Act 2025",
          "Passed May 28 2025, most provisions effective Jun 4 2025",
          "\"Innovation-first.\" No risk classification, no prohibited categories, no mandatory risk assessments, no monetary penalties. Sets principles and stakeholder roles; relies on 2024 AI Business Operator Guidelines for practical guidance."
        ]
      ]
    },
    {
      "heading": "Compliance compass — three questions to ask before you ship",
      "kind": "list",
      "body": "Most of the regimes above either give you a phased onramp or rely on existing instruments for enforcement. The questions that decide whether you're in scope:",
      "listItems": [
        "Where will users access your system? EU users → AI Act applies, full stop. California residents → SB 53 (if frontier-scale) and AB 2013 (if generative). NYC employees or candidates → Local Law 144 if your tool substantially screens them. Chinese public → Interim Measures and filing requirements.",
        "What's your compute? Above 10^25 FLOPs → EU GPAI systemic-risk obligations potentially apply. Above 10^26 FLOPs → California SB 53 in scope for the model itself, regardless of where you train it, if the model is made available to Californians.",
        "What domain are you deploying into? Employment, housing, credit, education, healthcare, biometrics, law enforcement, critical infrastructure → high-risk under the EU AI Act and the original Colorado AI Act; expect to need conformity assessment (EU), or transparency reports (California SB 53), or bias audits (NYC LL 144). Pure consumer entertainment or productivity → mostly only the transparency and content-labeling rails apply (EU Art 50, India IT Rules, voluntary disclosures elsewhere)."
      ]
    },
    {
      "heading": "What's likely to move between June 2026 and end-of-year",
      "kind": "list",
      "body": "Best-effort predictions, not forecasts. Each is anchored to a public roadmap or pending docket — not a hunch.",
      "listItems": [
        "EU AI Act: high-risk system obligations and Article 50 transparency rules apply from August 2 2026. First enforcement window for GPAI providers opens the same day.",
        "United States: the December 2025 preemption executive order's litigation is active. Expect circuit-court decisions on whether the federal government can condition funding on states repealing AI laws. NPR and constitutional-law commentators have already flagged Tenth Amendment concerns.",
        "Colorado: replacement act SB 26-189 takes effect June 30 2026, ending most of the original substantive obligations. Watch the AG's rule-making.",
        "Brazil: Chamber of Deputies special committee on PL 2338 is constituted; floor vote possible in second half of 2026, but no fixed date.",
        "UK: a frontier-AI bill has been consulted on but not introduced. Election cycle pressure may or may not push it onto the legislative calendar.",
        "California: more bills are queued — synthetic media disclosure, AI-in-healthcare, AI-in-hiring updates. The state is operating as the de facto national regulator on AI absent federal preemption."
      ]
    },
    {
      "heading": "A note on what we did not include",
      "kind": "callout",
      "body": "This page covers horizontal AI regulation. It does not cover: sector-specific AI rules (FDA guidance on AI/ML medical devices, EEOC technical assistance on AI in hiring, GDPR application to AI systems, the EU Digital Services Act's transparency duties on algorithmic recommendation, copyright litigation against foundation model providers, or the various national security and export-control regimes touching AI compute and model weights). Those are real and material, but each is a page-length subject of its own. If you came here looking for one of them, the citations below will get you to the primary sources fastest."
    }
  ],
  "citations": [
    {
      "source": "digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
      "claim": "Official European Commission page for the AI Act, with phased application timeline (entry into force August 1 2024; prohibited practices and AI literacy from February 2 2025; GPAI obligations from August 2 2025; high-risk and Article 50 from August 2 2026)."
    },
    {
      "source": "artificialintelligenceact.eu/article/99/",
      "claim": "Article 99 of the EU AI Act sets the three-tier penalty ceiling: €35M / 7% global turnover for prohibited practices, €15M / 3% for high-risk breaches, €7.5M / 1% for false information."
    },
    {
      "source": "digital-strategy.ec.europa.eu/en/policies/contents-code-gpai",
      "claim": "European Commission page for the General-Purpose AI Code of Practice published July 10 2025, with three chapters (Transparency, Copyright, Safety and Security)."
    },
    {
      "source": "en.wikipedia.org/wiki/Executive_Order_14110",
      "claim": "Biden Executive Order 14110 signed October 30 2023; required safety test reporting for dual-use foundation models above the relevant compute thresholds; rescinded by EO 14148 on January 20 2025."
    },
    {
      "source": "whitehouse.gov/presidential-actions/2025/01/removing-barriers-to-american-leadership-in-artificial-intelligence/",
      "claim": "Official White House text of Trump's January 23 2025 Executive Order 14179, 'Removing Barriers to American Leadership in Artificial Intelligence.'"
    },
    {
      "source": "whitehouse.gov/presidential-actions/2025/12/eliminating-state-law-obstruction-of-national-artificial-intelligence-policy/",
      "claim": "December 11 2025 executive order on national AI policy framework, establishing an AI Litigation Task Force and tying federal funding to state AI policy."
    },
    {
      "source": "npr.org/2025/12/11/nx-s1-5638562/trump-ai-david-sacks-executive-order",
      "claim": "NPR reporting that the December 2025 federal AI preemption executive order faces constitutional challenges, particularly on the spending-clause and Tenth Amendment grounds."
    },
    {
      "source": "leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202320240AB2013",
      "claim": "Official California legislative text of AB 2013, the Generative Artificial Intelligence Training Data Transparency Act, signed September 28 2024 and effective January 1 2026."
    },
    {
      "source": "leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202520260SB53",
      "claim": "Official California legislative text of SB 53, the Transparency in Frontier Artificial Intelligence Act, signed by Governor Newsom on September 29 2025."
    },
    {
      "source": "gov.ca.gov/2025/09/29/governor-newsom-signs-sb-53-advancing-californias-world-leading-artificial-intelligence-industry/",
      "claim": "California Governor's office announcement of SB 53 signing on September 29 2025, framing it as the first US state frontier-AI transparency statute."
    },
    {
      "source": "gov.ca.gov/wp-content/uploads/2024/09/SB-1047-Veto-Message.pdf",
      "claim": "Governor Newsom's official veto message for SB 1047 (Safe and Secure Innovation for Frontier AI Models Act) dated September 29 2024."
    },
    {
      "source": "leg.colorado.gov/bills/sb24-205",
      "claim": "Colorado General Assembly page for SB 24-205, the original Colorado AI Act creating high-risk AI deployer obligations effective February 1 2026; later postponed and replaced."
    },
    {
      "source": "nyc.gov/site/dca/about/automated-employment-decision-tools.page",
      "claim": "NYC Department of Consumer and Worker Protection page on Local Law 144, the Automated Employment Decision Tools law in force since July 5 2023."
    },
    {
      "source": "osc.ny.gov/state-agencies/audits/2025/12/02/enforcement-local-law-144-automated-employment-decision-tools",
      "claim": "NY State Comptroller audit (December 2025) finding that DCWP's enforcement of Local Law 144 between July 2023 and June 2025 has been weak and complaint-driven."
    },
    {
      "source": "chinalawtranslate.com/en/generative-ai-interim/",
      "claim": "China Law Translate's English text of China's Interim Measures for the Management of Generative AI Services, effective August 15 2023."
    },
    {
      "source": "en.wikipedia.org/wiki/Interim_Measures_for_the_Management_of_Generative_AI_Services",
      "claim": "Wikipedia summary citing Cyberspace Administration of China primary documents for the Interim Measures' scope (services with public opinion attributes or social mobilization capabilities) and Article 17 security-assessment requirement."
    },
    {
      "source": "loc.gov/item/global-legal-monitor/2025-05-23/brazil-senate-advances-discussions-on-bill-to-regulate-ai-use/",
      "claim": "Library of Congress global legal monitor noting Brazilian Senate approval of PL 2338/2023 on December 10 2024 and subsequent forwarding to the Chamber of Deputies."
    },
    {
      "source": "parl.ca/legisinfo/en/bill/44-1/c-27",
      "claim": "Canadian Parliament's official LEGISinfo page for Bill C-27 (containing AIDA), which died on the order paper following the January 6 2025 prorogation."
    },
    {
      "source": "ised-isde.canada.ca/site/innovation-better-canada/en/artificial-intelligence-and-data-act-aida-companion-document",
      "claim": "Innovation, Science and Economic Development Canada companion document for the proposed AIDA framework under Bill C-27."
    },
    {
      "source": "whitecase.com/insight-alert/japans-first-ai-legislation-becomes-law-focus-promoting-research-and-development-no",
      "claim": "White & Case summary of Japan's AI Promotion Act, passed May 28 2025 and effective June 4 2025, with no monetary penalties."
    },
    {
      "source": "fpf.org/blog/understanding-japans-ai-promotion-act-an-innovation-first-blueprint-for-ai-regulation/",
      "claim": "Future of Privacy Forum analysis describing Japan's AI Promotion Act as an innovation-first framework relying on principles and guidelines rather than risk-tiered obligations."
    },
    {
      "source": "siliconrepublic.com/business/uk-ai-safety-institute-renamed-new-focus-government",
      "claim": "Silicon Republic reporting Peter Kyle's February 14 2025 renaming of the UK AI Safety Institute to the AI Security Institute, signaling a national-security focus."
    },
    {
      "source": "medianama.com/2026/04/223-meity-ai-label-rules-mandates-continuous-disclosure/",
      "claim": "MediaNama coverage of India's MeitY IT Rules 2026 amendment, notified February 10 2026 and effective February 20 2026, requiring continuous labels on synthetically generated content."
    },
    {
      "source": "lw.com/en/insights/eu-ai-act-gpai-model-obligations-in-force-and-final-gpai-code-of-practice-in-place",
      "claim": "Latham & Watkins note that GPAI obligations under the EU AI Act took effect August 2 2025 and that Commission enforcement actions against GPAI providers begin one year later on August 2 2026."
    },
    {
      "source": "akingump.com/en/insights/ai-law-and-regulation-tracker/colorado-postpones-implementation-of-colorado-ai-act-sb-24-205",
      "claim": "Akin Gump tracker confirming Colorado Governor Polis signed SB 25B-004 on August 28 2025 postponing the Colorado AI Act, and subsequent replacement legislation SB 26-189 signed May 14 2026."
    }
  ],
  "crosslinks": [
    {
      "label": "Learn: AI policy primer",
      "href": "/learn"
    },
    {
      "label": "Research papers index",
      "href": "/research"
    },
    {
      "label": "OrangeBox local AI stack",
      "href": "/orangebox"
    },
    {
      "label": "Compare: EU vs US AI rules",
      "href": "/vs"
    },
    {
      "label": "Tools and references",
      "href": "/tools"
    },
    {
      "label": "B00KMakor — books for builders",
      "href": "/b00kmakor"
    }
  ]
};

const BREADCRUMB = [
  {
    "label": "AtomEons",
    "href": "/"
  },
  {
    "label": "Learn",
    "href": "/learn"
  },
  {
    "label": "regulation"
  }
];

export const metadata: Metadata = {
  title: "AI regulation tracker by jurisdiction · AtomEons /learn/regulation",
  description: "AI law moved from white papers to enforceable statute between 2023 and 2026. The center of gravity now sits in three places: Brussels, where the EU AI Act became the world's first horizontal AI statut…",
  alternates: { canonical: "https://atomeons.com/learn/regulation" },
  openGraph: {
    title: "AI regulation tracker by jurisdiction",
    description: "What's in force, what's pending, what's posture — as of June 2026",
    url: "https://atomeons.com/learn/regulation",
    type: "article",
  },
  robots: { index: true, follow: true },
};

export default function Page() {
  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "AI regulation tracker by jurisdiction",
    "description": "What's in force, what's pending, what's posture — as of June 2026",
    "author": { "@type": "Organization", "name": "AtomEons Systems Laboratory" },
    "publisher": { "@type": "Organization", "name": "AtomEons", "url": "https://atomeons.com" },
    "license": "https://creativecommons.org/licenses/by/4.0/",
    "isAccessibleForFree": true,
    "url": "https://atomeons.com/learn/regulation",
  };
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} />
      <GenericPage page={PAGE_DATA} breadcrumb={BREADCRUMB} />
    </>
  );
}
