import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "What we keep coming back to. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /watching · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ watching · films + TV",
    title: "What we keep coming back to.",
    stamp: "CINEMA",
    accent: "cyan",
    rightPrimary: "22",
    rightLabel: "works · honest notes",
    bottomReceipt: "atomeons.com/watching · CC-BY 4.0",
  });
}
