import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "One URL for your security team. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /vendor-pack · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ vendor pack · CISO-ready",
    title: "One URL for your security team.",
    stamp: "PROCUREMENT",
    accent: "gold",
    rightPrimary: "5",
    rightLabel: "sections · 8 procurement Q&A",
    bottomReceipt: "atomeons.com/vendor-pack · CC-BY 4.0",
  });
}
