import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "An instrument, not a content factory. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /b00kmakor/roadmap · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ B00KMAKR · roadmap",
    title: "An instrument, not a content factory.",
    stamp: "BINDING",
    accent: "pulse",
    rightPrimary: "6",
    rightLabel: "anti-roadmap clauses",
    bottomReceipt: "atomeons.com/b00kmakor/roadmap · CC-BY 4.0",
  });
}
