import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Letters that needed more room. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /dear-reader · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ dear reader · letters",
    title: "Letters that needed more room.",
    stamp: "LONG-FORM",
    accent: "cyan",
    rightPrimary: "5",
    rightLabel: "letters · irregular cadence",
    bottomReceipt: "atomeons.com/dear-reader · CC-BY 4.0",
  });
}
