import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "The mark behind every artifact. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /signature · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ signature · the operator's mark",
    title: "The mark behind every artifact.",
    stamp: "SIGNED",
    accent: "gold",
    rightPrimary: "Æ",
    rightLabel: "procedural · per-route · deterministic",
    bottomReceipt: "atomeons.com/signature · CC-BY 4.0",
  });
}
