import type { Metadata } from "next";
import { Calculator } from "@/app/_components/generic-page/Calculator";
import type { CalculatorSpec } from "@/app/_components/generic-page/types";

// Auto-materialized from wf_c1eaafe8-714 (nvidia-tier-50 workflow).
// Generated by .scripts/materialize-nvidia-tier-50.mjs.

const CALC_SPEC: CalculatorSpec = {
  "slug": "tools/cost-calculator",
  "title": "AI Cost Calculator",
  "subtitle": "What does your AI task actually cost per year?",
  "intro": "Most teams ship AI features without ever drawing a line from \"tokens per request\" to \"annual invoice.\" Then the invoice arrives and someone has to explain why a chatbot costs $40,000 a year, or why moving from Claude 3.5 Sonnet to Haiku quietly saved $28,000 with no quality drop on the actual workload.\n\nThis calculator closes that gap. You give it three honest numbers — average input tokens per task, average output tokens per task, tasks per day — and a provider/model choice. It returns cost per task, cost per month, and cost per year using realistic published prices as of June 2026.\n\nThe math is deliberately boring: input tokens times input price plus output tokens times output price, divided by one million, multiplied by run rate. No volume discounts assumed. No batch API discounts assumed. No caching credits assumed. Those things are real and they help — and they are out of scope here because they vary by contract, vary by month, and tempt people to be optimistic about their own usage. This is the upper-bound estimate. The number your CFO should believe before you negotiate it down.\n\nA few things the calculator does NOT include, and which you should think about separately. It does not model retries, tool calls, agent loops where one user task fans out into ten model calls, or systems where Claude generates a draft and GPT critiques it. Those multiply real cost by 3x to 10x. It does not include embedding costs, vector store costs, or the human review labor that often dominates the bill. It assumes \"local-ollama\" is free at the API line — but you are paying for the GPU, the electricity, and the engineer who keeps it running, so call it $0.0001/M tokens of opportunity cost and decide for yourself.\n\nUse this as a sanity check before you commit to a model. Run it on three workload sizes (today, 6 months, end of year) and look at the year-end number. If that number scares you, you have a model selection problem, not a usage problem.",
  "inputs": [
    {
      "name": "inputTokens",
      "label": "Average input tokens per task",
      "type": "number",
      "default": 2000,
      "min": 0,
      "max": 1000000,
      "step": 100,
      "unit": "tokens",
      "help": "Includes system prompt + user message + any context you pass in"
    },
    {
      "name": "outputTokens",
      "label": "Average output tokens per task",
      "type": "number",
      "default": 500,
      "min": 0,
      "max": 100000,
      "step": 50,
      "unit": "tokens",
      "help": "What the model writes back. Tends to be smaller than input unless you ask for long generations."
    },
    {
      "name": "tasksPerDay",
      "label": "Tasks per day",
      "type": "number",
      "default": 50,
      "min": 0,
      "max": 10000000,
      "step": 1,
      "unit": "tasks/day",
      "help": "One user-facing task = one set of input + output tokens. Not raw API calls."
    },
    {
      "name": "model",
      "label": "Provider / model",
      "type": "select",
      "default": "claude-3.5-sonnet",
      "help": "June 2026 published prices per 1M tokens. Local-ollama assumes $0 API cost (GPU/electric not included).",
      "options": [
        {
          "value": "claude-3.5-sonnet",
          "label": "Claude 3.5 Sonnet ($3 in / $15 out per 1M)"
        },
        {
          "value": "claude-3.5-haiku",
          "label": "Claude 3.5 Haiku ($0.80 in / $4 out per 1M)"
        },
        {
          "value": "gpt-4o",
          "label": "GPT-4o ($2.50 in / $10 out per 1M)"
        },
        {
          "value": "gpt-4o-mini",
          "label": "GPT-4o mini ($0.15 in / $0.60 out per 1M)"
        },
        {
          "value": "gemini-1.5-pro",
          "label": "Gemini 1.5 Pro ($1.25 in / $5 out per 1M, long context tier higher)"
        },
        {
          "value": "gemini-1.5-flash",
          "label": "Gemini 1.5 Flash ($0.075 in / $0.30 out per 1M)"
        },
        {
          "value": "local-ollama",
          "label": "Local (Ollama, self-hosted) — $0 API line"
        }
      ]
    }
  ],
  "computeDescription": "Each model has a published input price and output price per 1 million tokens. Cost per task = (input tokens times input price + output tokens times output price) divided by 1,000,000. Cost per month = cost per task times tasks per day times 30. Cost per year = cost per task times tasks per day times 365. Local-ollama is hardcoded to $0 at the API line (your GPU and electricity are real costs but live outside this calculator). No volume discount, no batch discount, no prompt caching modeled — this is the gross upper bound.",
  "computeFormula": [
    {
      "outputName": "costPerTask",
      "expression": "(inputTokens * (model === 'claude-3.5-sonnet' ? 3 : model === 'claude-3.5-haiku' ? 0.80 : model === 'gpt-4o' ? 2.50 : model === 'gpt-4o-mini' ? 0.15 : model === 'gemini-1.5-pro' ? 1.25 : model === 'gemini-1.5-flash' ? 0.075 : 0) + outputTokens * (model === 'claude-3.5-sonnet' ? 15 : model === 'claude-3.5-haiku' ? 4 : model === 'gpt-4o' ? 10 : model === 'gpt-4o-mini' ? 0.60 : model === 'gemini-1.5-pro' ? 5 : model === 'gemini-1.5-flash' ? 0.30 : 0)) / 1000000"
    },
    {
      "outputName": "costPerMonth",
      "expression": "(inputTokens * (model === 'claude-3.5-sonnet' ? 3 : model === 'claude-3.5-haiku' ? 0.80 : model === 'gpt-4o' ? 2.50 : model === 'gpt-4o-mini' ? 0.15 : model === 'gemini-1.5-pro' ? 1.25 : model === 'gemini-1.5-flash' ? 0.075 : 0) + outputTokens * (model === 'claude-3.5-sonnet' ? 15 : model === 'claude-3.5-haiku' ? 4 : model === 'gpt-4o' ? 10 : model === 'gpt-4o-mini' ? 0.60 : model === 'gemini-1.5-pro' ? 5 : model === 'gemini-1.5-flash' ? 0.30 : 0)) / 1000000 * tasksPerDay * 30"
    },
    {
      "outputName": "costPerYear",
      "expression": "(inputTokens * (model === 'claude-3.5-sonnet' ? 3 : model === 'claude-3.5-haiku' ? 0.80 : model === 'gpt-4o' ? 2.50 : model === 'gpt-4o-mini' ? 0.15 : model === 'gemini-1.5-pro' ? 1.25 : model === 'gemini-1.5-flash' ? 0.075 : 0) + outputTokens * (model === 'claude-3.5-sonnet' ? 15 : model === 'claude-3.5-haiku' ? 4 : model === 'gpt-4o' ? 10 : model === 'gpt-4o-mini' ? 0.60 : model === 'gemini-1.5-pro' ? 5 : model === 'gemini-1.5-flash' ? 0.30 : 0)) / 1000000 * tasksPerDay * 365"
    }
  ],
  "outputs": [
    {
      "name": "costPerTask",
      "label": "Cost per task",
      "format": "currency",
      "decimals": 4
    },
    {
      "name": "costPerMonth",
      "label": "Cost per month (30-day)",
      "format": "currency",
      "decimals": 2
    },
    {
      "name": "costPerYear",
      "label": "Cost per year (365-day)",
      "format": "currency",
      "decimals": 2
    }
  ],
  "examples": [
    {
      "scenario": "Customer support chatbot on Claude 3.5 Sonnet",
      "inputValues": {
        "inputTokens": 4000,
        "outputTokens": 600,
        "tasksPerDay": 500,
        "model": "claude-3.5-sonnet"
      },
      "explanation": "4K context window with retrieved docs, 600-token answer, 500 tickets/day. Sonnet at $3/$15 per 1M. Annual cost lands near $3,920 — defensible at this scale, but watch what happens if traffic 10x's."
    },
    {
      "scenario": "Same workload, dropped to Claude 3.5 Haiku",
      "inputValues": {
        "inputTokens": 4000,
        "outputTokens": 600,
        "tasksPerDay": 500,
        "model": "claude-3.5-haiku"
      },
      "explanation": "Identical task profile, swapped model. Haiku at $0.80/$4 per 1M cuts annual cost by ~73%. The right move IF Haiku passes your eval on the actual ticket distribution. Run the eval before you swap."
    },
    {
      "scenario": "Background classifier on GPT-4o mini",
      "inputValues": {
        "inputTokens": 800,
        "outputTokens": 50,
        "tasksPerDay": 10000,
        "model": "gpt-4o-mini"
      },
      "explanation": "High-volume tagging job — small context, tiny output, 10K runs/day. GPT-4o mini at $0.15/$0.60 keeps it under $550/year. This is the workload class where commercial APIs actually beat self-hosting on total cost."
    },
    {
      "scenario": "Long-context document analyzer on Gemini 1.5 Pro",
      "inputValues": {
        "inputTokens": 80000,
        "outputTokens": 2000,
        "tasksPerDay": 100,
        "model": "gemini-1.5-pro"
      },
      "explanation": "Whole-document ingestion at 80K input tokens — Gemini's long-context strength. 100 docs/day, 2K-token summary. Annual cost lands near $4,015. Watch the long-context tier — Gemini raises prices above 128K input."
    }
  ],
  "assumptions": [
    "Prices are June 2026 published API prices, no negotiated rate, no enterprise discount, no committed-use credit applied.",
    "Prompt caching, batch API (50% discount on OpenAI/Anthropic), and Gemini's context caching are NOT modeled — they can cut real cost by 30-90% on the right workload.",
    "One 'task' equals one model call. Agents, retries, and multi-step chains can multiply real cost by 3x-10x. Count those separately.",
    "Local-ollama is shown as $0 at the API line. Your GPU, electricity, and operator time are real and out of scope here.",
    "Output tokens are usually billed 3-5x higher than input tokens. The biggest cost lever is almost always 'make the model write less.'",
    "Gemini 1.5 Pro pricing tiers up for >128K input contexts. This calculator uses the base tier; long-context jobs will run higher.",
    "30 days/month and 365 days/year are flat assumptions. Bursty workloads (B2B Mon-Fri only) overestimate by ~30%.",
    "Token counts depend on tokenizer — Claude, GPT, and Gemini tokenize differently. Same English text can produce 5-15% different token counts across providers."
  ],
  "accent": "cyan"
};

const BREADCRUMB = [
  {
    "label": "AtomEons",
    "href": "/"
  },
  {
    "label": "Learn",
    "href": "/learn"
  },
  {
    "label": "calc",
    "href": "/learn/calc"
  },
  {
    "label": "tools",
    "href": "/learn/calc/tools"
  },
  {
    "label": "cost-calculator"
  }
];

export const metadata: Metadata = {
  title: "AI Cost Calculator · AtomEons calculator",
  description: "Most teams ship AI features without ever drawing a line from \"tokens per request\" to \"annual invoice.\" Then the invoice arrives and someone has to explain why a chatbot costs $40,000 a year, or why mo…",
  alternates: { canonical: "https://atomeons.com/learn/calc/tools/cost-calculator" },
  openGraph: {
    title: "AI Cost Calculator",
    description: "What does your AI task actually cost per year?",
    url: "https://atomeons.com/learn/calc/tools/cost-calculator",
    type: "article",
  },
  robots: { index: true, follow: true },
};

export default function Page() {
  return <Calculator spec={CALC_SPEC} breadcrumb={BREADCRUMB} heroImageSlug="calc-cost-calculator" heroImageAlt={"A single matte-black abacus bead on dark slate with bio-cyan rim light."} />;
}
