import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Every route, every edge. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /constellation · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ constellation · the lab as a graph",
    title: "Every route, every edge.",
    stamp: "INTERACTIVE",
    accent: "cyan",
    rightPrimary: "278",
    rightLabel: "routes · 648 edges · force-laid",
    bottomReceipt: "atomeons.com/constellation · CC-BY 4.0",
  });
}
