import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "What plays while the work happens. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /listening · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ listening · studio music",
    title: "What plays while the work happens.",
    stamp: "STUDIO",
    accent: "cyan",
    rightPrimary: "20",
    rightLabel: "albums · one-line notes",
    bottomReceipt: "atomeons.com/listening · CC-BY 4.0",
  });
}
