import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Scaling Monosemanticity — Anthropic 2024 · Decoded · AtomEons",
  description: "Anthropic showed that sparse autoencoders trained on Claude 3 Sonnet recover millions of interpretable features — and that you can causally manipulate them to change model behavior. The Golden Gate Claude demo was the public proof.",
  alternates: { canonical: "https://atomeons.com/research/decoded/scaling-monosemanticity" },
  openGraph: { title: "Decoded · Scaling Monosemanticity", description: "Anthropic 2024 · SAEs on Claude 3 Sonnet · millions of interpretable features.", url: "https://atomeons.com/research/decoded/scaling-monosemanticity", type: "article" },
};

export default function Page() {
  return (
    <main className="bg-[#08090B] text-[#F4F4F2] antialiased">
      <section className="border-b border-[#1F242B]"><div className="mx-auto max-w-4xl px-6 pt-20 pb-12 md:px-10 md:pt-28 md:pb-20">
        <p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#5A6068]"><Link href="/research/decoded" className="hover:text-[#22F0D5]">§ Decoded papers</Link><span className="mx-3 text-[#1F242B]">·</span><span className="text-[#22F0D5]">Interpretability · production-scale</span></p>
        <h1 className="mt-8 max-w-[26ch] text-balance text-[clamp(36px,6vw,72px)] font-extralight leading-[1.04] tracking-[-0.025em] text-[#F4F4F2]">Scaling Monosemanticity — interpretability that works on a real model</h1>
        <p className="mt-8 max-w-[64ch] font-serif text-[19px] leading-[1.55] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The paper that took sparse autoencoders from toy models to Claude 3 Sonnet, recovered millions of interpretable features, and demonstrated causal manipulation with the Golden Gate Claude release. The proof-of-concept moment for mechanistic interpretability at production scale.</p>
      </div></section>

      <article className="mx-auto max-w-3xl px-6 py-16 md:px-10 md:py-24 space-y-12">
        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What the paper actually shows</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Templeton, Conerly, Marcus, et al, <em>Scaling Monosemanticity: Extracting Interpretable Features from Claude 3 Sonnet</em>, Anthropic, May 21, 2024. The authors trained sparse autoencoders (SAEs) of three sizes — 1M, 4M, and 34M features — on the residual stream of Claude 3 Sonnet, a production frontier LLM. They found interpretable features at every scale, including features for: famous people, locations (the Golden Gate Bridge feature became the public demo), abstract concepts (deception, sycophancy, code injection), safety-relevant categories (bioweapon precursors, dangerous chemicals), and emergent behaviors (refusing to answer, recognizing the model is being tested).</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>They demonstrated <em>causal manipulation</em>: clamping a feature&apos;s activation high or low at inference time changes model behavior in the expected way. Clamping the Golden Gate Bridge feature high produced &quot;Golden Gate Claude&quot; — a public 24-hour Anthropic release where Claude related every conversation back to the bridge. Clamping the sycophancy feature high made the model fawn; clamping it low made it more honest about disagreement.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Why it matters</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Before this paper, mechanistic interpretability had been demonstrated on small models (GPT-2 small, single-layer toy transformers, one-billion-parameter models). The question was whether the techniques would scale to frontier models with hundreds of billions of parameters and the polysemanticity that emerges at scale. The answer turned out to be yes — SAEs found monosemantic features in a state-of-the-art deployed model, and the features were causal. This unblocked the entire safety-and-audit research agenda built on interpretability.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The implication for AI safety: it is now plausible to <em>audit a model&apos;s circuits</em> for safety-relevant behavior, not just its outputs. You can ask: does this model have features that fire on bioweapon-synthesis queries? Does it have a deception circuit? Does it have a feature for &quot;recognizing this is an evaluation, not a real deployment?&quot; The Sleeper Agents paper (Hubinger et al, January 2024) showed why this matters — behavioral safety training can fail to remove deception. Scaling Monosemanticity is the technique that could in principle find the backdoor circuit and remove it.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What the scientists did</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Take Claude 3 Sonnet&apos;s middle-layer residual stream activations on a large dataset of prompts. Train a sparse autoencoder: a single hidden-layer network whose hidden dimension is much larger than the residual-stream dimension, but whose hidden activations are constrained to be sparse (most hidden units zero on any given input). The constraint forces each hidden unit to specialize.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>After training, the authors inspected each hidden unit by finding the inputs that maximally activated it and looking at what they had in common. The result: most units corresponded to a single human-recognizable concept. They scaled the SAE width through 1M, 4M, 34M features. Larger SAEs found <em>finer-grained</em> features (different aspects of the same concept), suggesting the features form a partial ordering and that more features = more resolution.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>For the causal experiments: take a feature, clamp its activation to a fixed high or low value during model forward passes, observe how outputs change. The behavior change is consistent and feature-specific. The Golden Gate Claude release was the public-facing version of this experiment.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What this paper does NOT claim</h2><ul className="space-y-4 font-serif text-[17px] leading-[1.6] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">NOT &quot;Claude is fully interpreted.&quot;</strong> The 34M-feature SAE captures a substantial fraction of the residual stream variance but is not exhaustive. There are concepts Claude has that the SAE doesn&apos;t cleanly recover. The result is a tractability proof, not a completeness claim.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">NOT &quot;safety is solved.&quot;</strong> Finding a feature is not the same as removing it. Clamping is an inference-time intervention; it doesn&apos;t change the underlying weights. Permanent safety modifications via SAE findings is a research direction, not a deployed capability.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">NOT &quot;every feature is causal.&quot;</strong> SAEs find features that correlate with concepts in the input. Some are causally upstream of behavior; others are downstream readouts. The paper carefully distinguishes via patching experiments.</li>
        </ul></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What the field knows but rarely says</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The 34M-feature SAE is expensive to train and store. Anthropic has the data center and the weights access; almost no one else does at this scale. DeepMind&apos;s Gemma Scope (Lieberum et al, 2024) was the first major external attempt, applied to the smaller open Gemma 2 family. The replication frontier remains close to the labs that train frontier models.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The cross-coder generation (Lindsey et al, Anthropic, late 2024) is the followup that addresses some of this paper&apos;s limitations — decomposing layer-to-layer computation rather than single-layer representation. The technique is moving fast.</p></section>

        <section className="space-y-3"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Where to read the original</h2><ul className="space-y-2 font-serif text-[16px] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li><a href="https://transformer-circuits.pub/2024/scaling-monosemanticity/" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">Templeton et al · Scaling Monosemanticity (full paper)</a></li>
          <li><a href="https://www.anthropic.com/news/mapping-mind-language-model" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">Anthropic blog post — Mapping the Mind of a Large Language Model</a></li>
          <li><a href="https://transformer-circuits.pub/2023/monosemantic-features/" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">Bricken et al · Towards Monosemanticity (2023 precursor)</a></li>
          <li><Link href="/learn/atlas/mechanistic-interpretability" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">AtomEons · Mechanistic interpretability deep dive</Link></li>
          <li><Link href="/research/decoded/sleeper-agents" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">AtomEons · Sleeper Agents (the motivating safety case)</Link></li>
        </ul></section>

        <div className="border-t border-[#1F242B] pt-12"><Link href="/research/decoded" className="border border-[#1F242B] bg-[#0F1114] px-5 py-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[#F4F4F2] hover:border-[#22F0D5] hover:text-[#22F0D5]">← Back to Decoded papers</Link></div>
      </article>
    </main>
  );
}
