import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "What the lab actually says. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /correspondence · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ correspondence · inbox",
    title: "What the lab actually says.",
    stamp: "SANITIZED",
    accent: "cyan",
    rightPrimary: "7",
    rightLabel: "real email replies · with permission",
    bottomReceipt: "atomeons.com/correspondence · CC-BY 4.0",
  });
}
