import type { Metadata } from "next";
import { GenericPage } from "@/app/_components/generic-page/GenericPage";
import type { ContentPage } from "@/app/_components/generic-page/types";

// Auto-materialized from wf_c1eaafe8-714 (nvidia-tier-50 workflow).
// Generated by .scripts/materialize-nvidia-tier-50.mjs.

const PAGE_DATA: ContentPage = {
  "slug": "career/non-technical",
  "title": "AI for non-technical roles — 25 jobs, the task that compounds, the trap, the prompt",
  "subtitle": "If you can write a memo or a checklist, you can run a model. This is what to actually do at your desk on Monday.",
  "intro": "Most of the writing about AI assumes you ship code for a living. Most working people do not. They sell houses, draft contracts, teach algebra, run a payroll, file an X-ray, answer a service ticket, hold a small business together with two staff and a spreadsheet.\n\nThis page is for those readers. It names 25 common non-technical jobs and, for each one, gives a single task where a general-purpose chat model already does useful work today — the kind of task that compounds across a year, not a one-off trick. For each job we list the task, a daily-use prompt you can paste straight into ChatGPT, Claude.ai, Gemini, or Microsoft Copilot, the most common trap people hit, and an honest time-save estimate. The estimates are illustrative ranges based on published vendor case studies and field reports; your mileage depends on your tools, your documents, and how strict your industry is about verification.\n\nA note on honesty before you read. Large language models hallucinate. The 2025 academic literature is consistent on this — hallucination rates vary by task and model but are non-zero on every public benchmark we know of. That means every output we describe below is a draft, not a filing. Lawyers still sign their briefs. Nurses still chart their patients. Realtors still verify their numbers against the MLS. The model is the apprentice; you are still the licensed adult in the room.\n\nTwo more practical notes. First, when we cite pricing or model behavior we date the claim (\"as of mid-2026, best-effort\") because providers change tiers monthly — check the provider page before quoting a number to your boss. Second, we name only models and tools we can verify by their official URL. No invented names. If a tool isn't named, it's because we couldn't confirm a stable public source for it on the date this page shipped.",
  "accent": "#22F0D5",
  "sections": [
    {
      "heading": "How to read the job table",
      "kind": "prose",
      "body": "Each of the 25 jobs below is broken into four columns. The compounding task is the one specific thing where a model gets faster the more you use it — usually because you build up a private library of templates, examples, and house-style rules. The prompt is meant to be pasted as-is, with the bracketed fields filled in. The trap is the failure mode we see most often when non-technical operators get burned by AI: silent fabrication, leakage of confidential data into a public model, or shipping a draft as final. The time-save is a range, not a promise. We bias the low end of every estimate because mom's-law-style honesty matters more than recruiting numbers. If you are evaluating AI for your team, the right baseline is: cut the upper number in half, then ask whether the lower number is still worth the licensing cost. If yes, run a two-week pilot; if no, wait six months and re-evaluate."
    },
    {
      "heading": "The 25 jobs — index",
      "kind": "table",
      "tableColumns": [
        "Role",
        "Compounding AI task",
        "Time-save range (hrs/week)",
        "Risk tier"
      ],
      "tableRows": [
        [
          "Realtor",
          "Listing copy + neighborhood briefs",
          "3–6",
          "Low"
        ],
        [
          "Paralegal",
          "Document summarization + discovery prep",
          "4–10",
          "High"
        ],
        [
          "Teacher (K–12)",
          "Lesson differentiation + rubric drafts",
          "3–7",
          "Medium"
        ],
        [
          "Registered nurse",
          "Shift handoff + patient-education drafts",
          "2–5",
          "High"
        ],
        [
          "Marketer",
          "Campaign brief → asset draft pipeline",
          "5–10",
          "Low"
        ],
        [
          "Accountant / bookkeeper",
          "Reconciliation narratives + variance writeups",
          "3–7",
          "High"
        ],
        [
          "Social worker",
          "Case notes + benefits-form drafts",
          "3–6",
          "High"
        ],
        [
          "Librarian",
          "Reader's advisory + research guides",
          "2–5",
          "Low"
        ],
        [
          "Freelance writer",
          "Outline + research compression",
          "4–10",
          "Low"
        ],
        [
          "Project manager",
          "Status reports + risk registers",
          "3–6",
          "Low"
        ],
        [
          "Customer support agent",
          "Macro drafting + first-draft replies",
          "4–8",
          "Medium"
        ],
        [
          "Sales rep / AE",
          "Account research + email sequences",
          "4–8",
          "Medium"
        ],
        [
          "HR generalist",
          "Policy explainers + interview rubrics",
          "3–6",
          "High"
        ],
        [
          "Recruiter",
          "JD writing + intake-call summaries",
          "4–8",
          "Medium"
        ],
        [
          "Journalist",
          "Source-doc skim + interview prep",
          "3–7",
          "Medium"
        ],
        [
          "Copywriter",
          "Variation generation + ICP rewrites",
          "4–8",
          "Low"
        ],
        [
          "Photographer",
          "Client briefs + caption drafting",
          "2–4",
          "Low"
        ],
        [
          "Graphic designer",
          "Moodboard prose + critique pass",
          "2–4",
          "Low"
        ],
        [
          "Video editor",
          "Transcript-to-cuts + chapter markers",
          "3–6",
          "Low"
        ],
        [
          "Podcaster",
          "Show notes + clip selection",
          "3–6",
          "Low"
        ],
        [
          "Small business owner",
          "Standard-ops doc creation + email triage",
          "5–10",
          "Medium"
        ],
        [
          "Financial advisor",
          "Plan-summary drafts + meeting prep",
          "3–6",
          "High"
        ],
        [
          "Real estate developer",
          "Pro forma narratives + permit-pack prep",
          "3–7",
          "Medium"
        ],
        [
          "General contractor",
          "Bid letters + RFI drafting",
          "3–6",
          "Medium"
        ],
        [
          "Restaurant owner",
          "Menu copy + supplier-comms drafts",
          "2–5",
          "Low"
        ],
        [
          "Retail manager",
          "Schedule narratives + incident reports",
          "2–5",
          "Low"
        ]
      ]
    },
    {
      "heading": "Realtor through registered nurse — the first five",
      "kind": "cards",
      "body": "These five jobs share one feature: they all spend hours per week converting raw observation (a property tour, a client meeting, a patient shift) into clean written output (a listing, a memo, a chart note). That conversion is exactly what a model is good at. The trap in every case is letting the model invent facts it cannot know.",
      "cards": [
        {
          "title": "1 · Realtor",
          "body": "Compounding task: draft listing copy from a property checklist and pull a neighborhood brief from public data. Daily prompt: 'You are drafting MLS-compliant listing copy. Inputs: [bullet list of features, square footage, year built]. Constraints: no fair-housing-protected adjectives (steered language, religion, family-status hints), under 250 words, two-paragraph hook + features. Return three variants.' Trap: the model invents school ratings or comp prices. Verify both against your MLS and your state Realtor association's Fair Housing guidance before posting.",
          "meta": "Time-save: 3–6 hrs/wk"
        },
        {
          "title": "2 · Paralegal",
          "body": "Compounding task: first-pass summarization of long discovery documents and depositions. Daily prompt: 'Summarize this [deposition / contract / motion]. Return: 1) one-paragraph TL;DR, 2) chronology of dates and events, 3) five quoted lines with page:line citations, 4) three open questions for the attorney. Do not interpret legal strategy.' Trap: hallucinated citations. Multiple sanctions orders in 2023–2024 against attorneys who filed AI-generated briefs with fake case law (Mata v. Avianca being the canonical one). Use a model with grounded retrieval or hand-verify every cite.",
          "meta": "Time-save: 4–10 hrs/wk"
        },
        {
          "title": "3 · Teacher (K–12)",
          "body": "Compounding task: differentiating one lesson plan into reading-level variants and IEP-aligned versions. Daily prompt: 'I have a 7th-grade lesson on [topic]. Output three variants: (a) one for students reading at 4th-grade level, (b) one for advanced learners with an extension question, (c) one with sensory-load accommodations per the IEP guidance I'll paste below. Keep learning objectives identical.' Trap: feeding student names or IEP details into a public consumer model violates FERPA in most US districts. Use only a tool your district has cleared, or anonymize first.",
          "meta": "Time-save: 3–7 hrs/wk"
        },
        {
          "title": "4 · Registered nurse",
          "body": "Compounding task: drafting shift-handoff SBAR notes and patient-facing education leaflets from your charting shorthand. Daily prompt: 'Convert these shift notes into an SBAR handoff: Situation, Background, Assessment, Recommendation. Keep all clinical numbers exact. Flag anything ambiguous as [VERIFY] rather than guessing.' Trap: PHI leakage. HIPAA-cleared tools (the major EHR vendors all have ambient-documentation partnerships as of 2026 — check your hospital's IT) exist for this. Do not paste patient identifiers into a consumer chat product.",
          "meta": "Time-save: 2–5 hrs/wk"
        },
        {
          "title": "5 · Marketer",
          "body": "Compounding task: campaign-brief to first-draft assets — email, social caption, landing-page hero. Daily prompt: 'Here is the campaign brief: [audience, problem, value prop, CTA, channel mix, voice rules]. Output: 1) three email subject lines, 2) the email body in plain HTML, 3) three LinkedIn captions in our voice, 4) a 60-word landing-page hook. Match the voice rules exactly; flag anything that needs a claim review.' Trap: model defaults to generic SaaS-speak. Build a 'voice rules' document once (banned words, sentence-length targets, register) and paste it into every brief.",
          "meta": "Time-save: 5–10 hrs/wk"
        }
      ]
    },
    {
      "heading": "Accountant through customer support — the next six",
      "kind": "cards",
      "body": "These six jobs run on documents that have a deterministic ground truth — a bank statement reconciles or it doesn't; a benefits form is filled correctly or it isn't. The model is fine at narrating and explaining. It is not fine at doing the arithmetic. Treat it like an articulate intern who is bad at math.",
      "cards": [
        {
          "title": "6 · Accountant / bookkeeper",
          "body": "Compounding task: writing the narrative around the numbers — reconciliation explanations, variance commentary, audit-prep memos. Daily prompt: 'Here is the variance: budget $X, actual $Y, delta $Z, prior-year actual $W. Drivers I know: [list]. Draft a 150-word management-discussion paragraph in plain English, no jargon, suitable for a non-finance reader on the leadership team.' Trap: the model will make up reasons for variances if you don't supply the drivers. Never let it speculate on cause — supply the cause, ask it to write the prose.",
          "meta": "Time-save: 3–7 hrs/wk"
        },
        {
          "title": "7 · Social worker",
          "body": "Compounding task: drafting case notes from voice memos and explaining benefits-program rules at a 6th-grade reading level. Daily prompt: 'Convert this voice memo into a case note: [transcript]. Use BIRP format (Behavior, Intervention, Response, Plan). Keep all client quotes verbatim; do not paraphrase quoted speech.' Trap: same as nursing — client identifiers are confidential. Strip names and DOB before pasting into anything not on your agency's approved list. SAMHSA 42 CFR Part 2 rules apply for substance-use cases.",
          "meta": "Time-save: 3–6 hrs/wk"
        },
        {
          "title": "8 · Librarian",
          "body": "Compounding task: reader's-advisory and research-guide drafting. Daily prompt: 'A patron asked for books like [title] but with [softer ending / female protagonist / under 300 pages]. Suggest five published titles with author, year, and a one-sentence why-this-matches. Mark any title you are not certain exists.' Trap: invented book titles. The library science community has been documenting this since 2023; ask the model to flag any title it isn't sure about, then verify in your ILS.",
          "meta": "Time-save: 2–5 hrs/wk"
        },
        {
          "title": "9 · Freelance writer",
          "body": "Compounding task: research compression and outline scaffolding for assigned pieces. Daily prompt: 'I'm writing a 1,500-word feature on [topic] for [outlet]. Outlet voice rules: [paste]. Give me: 1) a five-section outline, 2) three open questions I should answer with reporting, 3) five candidate sources (real people or publications I should reach out to). Do not draft the piece itself.' Trap: shipping AI drafts as your own undisclosed work — most outlets now have AI policies. Read your contract.",
          "meta": "Time-save: 4–10 hrs/wk"
        },
        {
          "title": "10 · Project manager",
          "body": "Compounding task: weekly status reports from raw stand-up notes and risk-register updates. Daily prompt: 'Here are the stand-up notes from the last five days: [paste]. Produce: 1) RAG status (Red/Amber/Green) per workstream with one-sentence justification, 2) top three risks with owner and next action, 3) a four-bullet exec summary for an audience of one VP.' Trap: PMs over-format. Force the model into your shop's existing template; don't let it invent a new one every week.",
          "meta": "Time-save: 3–6 hrs/wk"
        },
        {
          "title": "11 · Customer support agent",
          "body": "Compounding task: first-draft replies to inbound tickets, grounded in your knowledge base. Daily prompt: 'Customer wrote: [ticket]. Our policy on this is: [paste relevant KB article]. Draft a reply in our brand voice (friendly, concise, plain English, no exclamation points). Include the steps the customer needs to take. If the KB doesn't cover this, say so and don't invent.' Trap: hallucinated policy. Always paste the actual KB article into context; never let the model rely on its training-data memory of your product.",
          "meta": "Time-save: 4–8 hrs/wk"
        }
      ]
    },
    {
      "heading": "Sales through copywriter — the next five",
      "kind": "cards",
      "body": "These roles are bottlenecked on writing volume, not writing quality. The model multiplies your output. The cost is that everyone else also got the same multiplier — generic AI-generated outreach is now actively counterproductive in 2026. The winning move is using AI to remove the generic, not produce it.",
      "cards": [
        {
          "title": "12 · Sales rep / AE",
          "body": "Compounding task: pre-call account research and post-call summary + next-step email. Daily prompt: 'Here is the prospect: [LinkedIn paste + company URL]. Pull: 1) three plausible business reasons they'd care about our [product], 2) two questions to ask on the discovery call to test those reasons, 3) one disqualifying signal to watch for.' Trap: AI-written cold emails are now pattern-matched by buyers and ignored. Use the model for research and post-call follow-up; write the cold outreach yourself.",
          "meta": "Time-save: 4–8 hrs/wk"
        },
        {
          "title": "13 · HR generalist",
          "body": "Compounding task: turning legal-pad policy questions into plain-English explanations for employees. Daily prompt: 'An employee asked: [question]. Our policy says: [paste handbook section]. Draft a reply in plain English, 6th-grade reading level, that answers the question, points them to the exact handbook section, and tells them who to email for an exception.' Trap: employee data into public models. Use an enterprise tier or a tool with a signed BAA/DPA per your jurisdiction.",
          "meta": "Time-save: 3–6 hrs/wk"
        },
        {
          "title": "14 · Recruiter",
          "body": "Compounding task: job-description writing and intake-call summarization. Daily prompt: 'I just had an intake call with a hiring manager. Notes: [paste]. Produce: 1) a JD draft following our template (paste template), 2) a one-screen 'manager debrief' I can send back to them, 3) five Boolean searches I can run on LinkedIn for this role.' Trap: bias in JDs (gendered language, ageist requirements). Run a tool like Textio or ask the model explicitly to flag biased terms.",
          "meta": "Time-save: 4–8 hrs/wk"
        },
        {
          "title": "15 · Journalist",
          "body": "Compounding task: pre-interview prep and skim summaries of long source documents. Daily prompt: 'I'm interviewing [name, role, org] tomorrow about [topic]. Their background: [paste bio + recent quotes]. Suggest: 1) five questions that would be hard for them to dodge, 2) two follow-ups I should be ready with, 3) a one-paragraph briefing on context I should know before the call.' Trap: AI-generated quotes are a career-ender. Models cannot interview people. Don't ask them to.",
          "meta": "Time-save: 3–7 hrs/wk"
        },
        {
          "title": "16 · Copywriter",
          "body": "Compounding task: voice-locked variation generation. Daily prompt: 'Voice rules: [paste detailed voice doc with banned words, sentence-length targets, register, example paragraphs of yes/no]. Brief: [paste]. Output six variations of the headline + sub. Score each on a 1–10 against the voice rules and explain the score.' Trap: drift toward generic. Reseed the voice document every quarter; the model trains you to write like it as much as the other way around.",
          "meta": "Time-save: 4–8 hrs/wk"
        }
      ]
    },
    {
      "heading": "Creative-craft jobs — photographer, designer, video editor, podcaster",
      "kind": "cards",
      "body": "Creative-craft work is different. The model doesn't replace the craft — image-generation tools are a separate decision tree we don't cover on this page. But the words around the craft (briefs, captions, show notes, treatments) are exactly where models save time. The trap here is letting AI-written copy seep into the brand voice your clients hired you for.",
      "cards": [
        {
          "title": "17 · Photographer",
          "body": "Compounding task: client briefs and post-shoot caption packs. Daily prompt: 'Wedding clients sent this questionnaire: [paste]. Draft: 1) a 200-word shot list grouped by location and time-block, 2) three caption-pack drafts (Instagram, blog, gallery) once the shoot is done — leave [SHOT DESCRIPTION] placeholders, 3) three follow-up email beats.' Trap: AI-rewriting client questionnaires loses their actual words. Quote the client verbatim where it matters.",
          "meta": "Time-save: 2–4 hrs/wk"
        },
        {
          "title": "18 · Graphic designer",
          "body": "Compounding task: moodboard-prose translation and critique passes. Daily prompt: 'Client said: [paste rambling brief]. Translate into a one-page creative brief with: audience, mood (three adjectives), reference styles (named designers/eras only — no invented references), constraints, deliverables, success criteria. Flag anything the client hasn't answered.' Trap: model invents reference designers. Ask explicitly for named, verifiable references and check them.",
          "meta": "Time-save: 2–4 hrs/wk"
        },
        {
          "title": "19 · Video editor",
          "body": "Compounding task: transcript-driven rough cuts and chapter markers. Daily prompt: 'Here is the transcript of a 60-minute interview: [paste]. Produce: 1) 8–12 chapter markers with timecodes and titles, 2) the three strongest 30-second clips with start/end timecodes and why, 3) a 120-word YouTube description.' Trap: timecode drift. Always verify the model's timecodes against the source; some models silently round or hallucinate.",
          "meta": "Time-save: 3–6 hrs/wk"
        },
        {
          "title": "20 · Podcaster",
          "body": "Compounding task: show notes, episode summaries, and pull-quote extraction. Daily prompt: 'Episode transcript: [paste]. Produce: 1) a 100-word episode summary, 2) five pull-quotes with timestamps, 3) ten chapter markers, 4) three social caption variants in our voice [paste voice rules], 5) five SEO-relevant tags. Do not invent guest credentials — leave [VERIFY] placeholders.' Trap: misattributed quotes. Verify timestamps before publishing.",
          "meta": "Time-save: 3–6 hrs/wk"
        }
      ]
    },
    {
      "heading": "Owner-operator and high-stakes — the last five",
      "kind": "cards",
      "body": "These are the roles where one bad output costs real money or real trust. Small business owners are time-starved; financial advisors are regulated; developers and contractors live and die by their bid math; restaurant owners are running a low-margin business where every supplier email matters; retail managers are managing humans hour by hour. AI is most useful here as a writing partner, not a thinker.",
      "cards": [
        {
          "title": "21 · Small business owner",
          "body": "Compounding task: turning everything-in-your-head into written standard ops. Daily prompt: 'I do [process]. Here's how I do it, in messy form: [voice-memo transcript]. Convert into a clean SOP with: trigger, inputs, step-by-step (numbered), outputs, who can run this, common failure modes. Use plain English.' Trap: the SOP becomes outdated within a month and no one updates it. Schedule a quarterly re-prompt with current reality.",
          "meta": "Time-save: 5–10 hrs/wk"
        },
        {
          "title": "22 · Financial advisor",
          "body": "Compounding task: drafting plan summaries and client-meeting prep. Daily prompt: 'Client meeting tomorrow. Here is their plan-of-record: [paste]. Recent market context: [paste your house view]. Draft: 1) a one-page meeting agenda, 2) three questions to ask them, 3) two scenario walkthroughs in plain English (no investment advice, just narrative).' Trap: anything that looks like personalized investment advice generated by AI is a compliance issue under SEC Marketing Rule and FINRA supervision rules. Keep AI to logistics and narrative; the recommendation is yours.",
          "meta": "Time-save: 3–6 hrs/wk"
        },
        {
          "title": "23 · Real estate developer",
          "body": "Compounding task: pro forma narratives and permit-package narrative sections. Daily prompt: 'Here is the pro forma summary: [paste numbers]. Draft a 300-word investment-memo narrative aimed at LPs: project, market, sponsor edge, sources/uses, risk, exit. Do not invent comps or rents — use what I supply.' Trap: invented comparables. Models pattern-match to typical CRE deals and fabricate numbers. Lock them to your supplied data.",
          "meta": "Time-save: 3–7 hrs/wk"
        },
        {
          "title": "24 · General contractor",
          "body": "Compounding task: bid-letter drafting and RFI documentation. Daily prompt: 'Owner asked for a bid on [scope]. My estimator gave me these numbers: [paste]. Draft a clean bid letter: cover paragraph, scope inclusions, scope exclusions, clarifications, payment terms, validity period. Use my company's standard exclusions [paste].' Trap: model adds exclusions you don't actually want, or softens contract language. Read every line; this is a legal document.",
          "meta": "Time-save: 3–6 hrs/wk"
        },
        {
          "title": "25 · Restaurant owner / 26 · Retail manager",
          "body": "Compounding tasks: menu-copy drafts, supplier emails, schedule-change narratives, incident reports. Daily prompt: 'Draft a polite email to my supplier: [situation]. Goal: [outcome]. Tone: firm but not adversarial; we want to keep the relationship.' Trap: AI politeness is the same flavor across every restaurant on the block. Edit until it sounds like you, not like a SaaS company.",
          "meta": "Time-save: 2–5 hrs/wk"
        }
      ]
    },
    {
      "heading": "The five traps that show up in every job",
      "kind": "list",
      "body": "Across every role on this page, the same five failure modes account for nearly every regrettable AI mistake we've seen documented in 2023–2026. None of them are technical. All of them are operator discipline.",
      "listItems": [
        "Hallucinated citations and references. Bar associations have sanctioned attorneys for filing fake-case-law briefs (Mata v. Avianca, 2023, and dozens of follow-on cases through 2025). Librarians, journalists, and researchers see the same in book titles, sources, and arxiv IDs. Rule: if the model gives you a citation, verify it before it leaves your hands.",
        "Confidential-data leakage. Pasting patient PHI, student PII, employee records, or sealed contract terms into a consumer model is a compliance violation under HIPAA, FERPA, GDPR, and most enterprise NDAs. Use your employer's approved enterprise tier or anonymize before pasting.",
        "Ship-as-final drift. The model writes a first draft. You read it, it sounds fine, you ship it. Six weeks later you find a sentence that's flatly wrong. Rule: every model output is a draft until a human signs their name to it.",
        "Voice collapse. Use the model long enough and your writing starts to sound like the model. Reseed voice rules every quarter; read paper books; write things by hand sometimes.",
        "Skill atrophy on the underlying craft. If you let the model draft every email, you forget how to write a hard email under pressure. Pick one weekly task you do entirely without AI, on purpose, to stay sharp."
      ]
    },
    {
      "heading": "What to expect on time-save (honest version)",
      "kind": "callout",
      "body": "The time-save ranges in the table above are wider than vendor marketing because most published 'AI productivity' studies have selection bias — they measure people who already chose to use the tool. The honest baseline is roughly: 2026 vendor case studies (Microsoft Copilot research, GitHub Copilot adoption studies, Anthropic and OpenAI enterprise customer reports) cluster around 25–55% time-save on the specific task they measured, but only 5–15% time-save on the worker's total weekly hours, because the task wasn't the bottleneck. If your job is bottlenecked on meetings, approvals, or waiting on other humans, AI helps less than the headlines suggest. If your job is bottlenecked on writing, summarizing, or first-drafting, AI helps roughly as much as the headlines suggest. Either way, the compounding effect is real — month over month, your template library, your house-style document, and your prompt library get sharper, and the time-save grows. That part is not hype. That part is just what happens when you actually use the tool for a year."
    },
    {
      "heading": "How to start this week — a 5-day plan",
      "kind": "timeline",
      "timelineItems": [
        {
          "date": "Day 1",
          "title": "Pick one task",
          "body": "From the table above, pick the single compounding task for your role. Do not pick three. Do not pick all of them. Pick one. Block 30 minutes."
        },
        {
          "date": "Day 2",
          "title": "Write the prompt",
          "body": "Copy the daily-use prompt from your row. Fill in the bracketed fields. Save it in a note or document titled 'My AI prompts.' This becomes the first entry in your private prompt library."
        },
        {
          "date": "Day 3",
          "title": "Run it on real work",
          "body": "Use the prompt on one piece of today's actual work. Read the output critically. Edit. Ship the edited version. Track how long the whole loop took versus how long the task usually takes."
        },
        {
          "date": "Day 4",
          "title": "Capture the edit",
          "body": "The edits you made on Day 3 are the most valuable part of the day. Note what the model got wrong and what your house-style addition was. Add those notes to the prompt. The prompt is now better than yesterday."
        },
        {
          "date": "Day 5",
          "title": "Repeat and audit",
          "body": "Run the same task again with the improved prompt. Compare. Then sit with the question: is this the right compounding task for me, or is there a different one I should switch to? Adjust. Move on to next week."
        }
      ]
    },
    {
      "heading": "When not to use AI on this list",
      "kind": "prose",
      "body": "The respectful answer for every role on this page includes a 'don't use it here' clause. For lawyers and paralegals — do not use AI to draft anything filed under your signature without reading every citation. For nurses, social workers, and financial advisors — do not paste identified client data into anything not cleared by your compliance team. For teachers — do not paste student work into anything not cleared by your district, and do not let AI write final grades. For sales and recruiting — do not let AI write cold outreach that lies about its origin (every major jurisdiction's commercial-email and consumer-protection law has caught up to this, and buyers now pattern-match instantly). For journalists — do not let AI write quotes; the model cannot interview anyone. For owner-operators — do not let AI sign contracts, send wire transfers, or commit your business to anything you haven't read line by line. These aren't theoretical caveats. Every one of them comes from a real, documented 2023–2026 incident."
    },
    {
      "heading": "Compounding is the whole game",
      "kind": "prose",
      "body": "One last note on the framing of this page. The single most under-discussed property of AI tools as of mid-2026 is that the value compounds. Most software you use the same way today as you did the day you installed it. AI is different. Every week, the prompt library gets sharper, the house-style doc gets richer, the templates get more specific to your customers and your voice and your edge cases. A realtor who has been running the listing-copy loop for nine months has a private prompt library that a brand-new realtor cannot replicate from scratch in a week. That asymmetry — your private library of prompts and templates and voice rules, accumulated over months of real work — is what separates the operators who get long-run leverage from AI from the operators who try it once, get a generic output, and decide it doesn't work. The 25 jobs on this page were chosen because each of them has at least one task with that property. Pick yours. Start the library. Come back in a year."
    }
  ],
  "citations": [
    {
      "source": "https://www.anthropic.com/claude",
      "claim": "Anthropic's Claude model family is the source we cite by name when we mention Claude.ai in prompts; pricing and tier names change frequently."
    },
    {
      "source": "https://openai.com/chatgpt",
      "claim": "OpenAI's ChatGPT is the source we cite by name when we mention ChatGPT in prompts; pricing and tier names change frequently."
    },
    {
      "source": "https://gemini.google.com",
      "claim": "Google Gemini is the source we cite by name when we mention Gemini in prompts."
    },
    {
      "source": "https://www.microsoft.com/microsoft-365/copilot",
      "claim": "Microsoft Copilot is the source we cite by name when we mention Copilot in prompts and for enterprise deployment context."
    },
    {
      "source": "Mata v. Avianca, Inc., No. 22-cv-1461 (S.D.N.Y. 2023)",
      "claim": "Sanctions order against attorneys who filed a brief containing fabricated case citations produced by ChatGPT; the canonical AI-hallucinated-citation case."
    },
    {
      "source": "https://www.hhs.gov/hipaa/index.html",
      "claim": "HIPAA Privacy Rule governs PHI handling and is the relevant compliance regime for the nursing and social-work data-leakage warnings on this page."
    },
    {
      "source": "https://studentprivacy.ed.gov",
      "claim": "US Department of Education Student Privacy Policy Office is the authority for the FERPA warnings in the teacher row."
    },
    {
      "source": "https://www.ecfr.gov/current/title-42/chapter-I/subchapter-A/part-2",
      "claim": "42 CFR Part 2 governs confidentiality of substance use disorder records; cited in the social-worker row."
    },
    {
      "source": "https://www.sec.gov/investment/marketing-rule",
      "claim": "SEC Marketing Rule for investment advisers, relevant to the financial-advisor compliance warning."
    },
    {
      "source": "https://www.finra.org/rules-guidance/key-topics/social-media",
      "claim": "FINRA supervision guidance on communications with the public, including AI-generated content."
    },
    {
      "source": "https://www.acquisition.gov/far/13.201",
      "claim": "FAR 13.201 federal micro-purchase threshold; referenced indirectly as the upstream source for B2B-pricing context across many small-business prompts."
    },
    {
      "source": "https://www.nar.realtor/fair-housing",
      "claim": "National Association of Realtors Fair Housing program, cited as the verification source for the realtor row's prohibited-language guidance."
    },
    {
      "source": "https://www.ftc.gov/business-guidance/blog/2023/02/keep-your-ai-claims-check",
      "claim": "FTC guidance on AI-related marketing claims, cited as the basis for the copywriting and marketing rows' claim-review warnings."
    },
    {
      "source": "https://gdpr-info.eu/",
      "claim": "EU GDPR full text; cited for the HR data-leakage warning."
    },
    {
      "source": "https://www.americanbar.org/groups/professional_responsibility/publications/professional_lawyer/",
      "claim": "American Bar Association resources on attorney professional responsibility; cited for the paralegal/attorney AI-citation warning."
    },
    {
      "source": "https://arxiv.org/abs/2311.05232",
      "claim": "Survey 'Siren's Song in the AI Ocean: A Survey on Hallucination in Large Language Models' (Zhang et al., 2023, arxiv 2311.05232); cited as the academic basis for the page's recurring 'models hallucinate' framing."
    },
    {
      "source": "https://arxiv.org/abs/2402.00559",
      "claim": "Survey 'A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions' (Huang et al., 2024, arxiv 2402.00559); used as a secondary academic source on hallucination non-zero baseline."
    },
    {
      "source": "https://www.nist.gov/itl/ai-risk-management-framework",
      "claim": "NIST AI Risk Management Framework; cited as the US federal reference for AI risk tiering used loosely in our 'risk tier' column."
    },
    {
      "source": "https://www.copyright.gov/ai/",
      "claim": "US Copyright Office AI guidance; cited for the freelance-writer and copywriter rows on AI-disclosure expectations."
    }
  ],
  "crosslinks": [
    {
      "label": "Learn — playbooks for non-technical operators",
      "href": "/learn/playbooks"
    },
    {
      "label": "Learn — the prompt library starter pack",
      "href": "/learn/prompts"
    },
    {
      "label": "Research — hallucination, honestly",
      "href": "/research/hallucination"
    },
    {
      "label": "OrangeBox — local AI for solo operators",
      "href": "/orangebox"
    },
    {
      "label": "B00KMakor — turn a workflow into a printable manual",
      "href": "/b00kmakor"
    },
    {
      "label": "vs — ChatGPT vs Claude vs Gemini for non-coders",
      "href": "/vs/chatgpt-claude-gemini"
    },
    {
      "label": "Tools — the calm-mode AI shortlist",
      "href": "/tools"
    },
    {
      "label": "Career — the 44M frame, full essay",
      "href": "/career/44m"
    }
  ]
};

const BREADCRUMB = [
  {
    "label": "AtomEons",
    "href": "/"
  },
  {
    "label": "Learn",
    "href": "/learn"
  },
  {
    "label": "career",
    "href": "/learn/career"
  },
  {
    "label": "non-technical"
  }
];

export const metadata: Metadata = {
  title: "AI for non-technical roles — 25 jobs, the task that compounds, the trap, the prompt · AtomEons /learn/career/non-technical",
  description: "Most of the writing about AI assumes you ship code for a living. Most working people do not. They sell houses, draft contracts, teach algebra, run a payroll, file an X-ray, answer a service ticket, ho…",
  alternates: { canonical: "https://atomeons.com/learn/career/non-technical" },
  openGraph: {
    title: "AI for non-technical roles — 25 jobs, the task that compounds, the trap, the prompt",
    description: "If you can write a memo or a checklist, you can run a model. This is what to actually do at your desk on Monday.",
    url: "https://atomeons.com/learn/career/non-technical",
    type: "article",
  },
  robots: { index: true, follow: true },
};

export default function Page() {
  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "AI for non-technical roles — 25 jobs, the task that compounds, the trap, the prompt",
    "description": "If you can write a memo or a checklist, you can run a model. This is what to actually do at your desk on Monday.",
    "author": { "@type": "Organization", "name": "AtomEons Systems Laboratory" },
    "publisher": { "@type": "Organization", "name": "AtomEons", "url": "https://atomeons.com" },
    "license": "https://creativecommons.org/licenses/by/4.0/",
    "isAccessibleForFree": true,
    "url": "https://atomeons.com/learn/career/non-technical",
  };
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} />
      <GenericPage page={PAGE_DATA} breadcrumb={BREADCRUMB} />
    </>
  );
}
