import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "What the lab has shipped. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /timeline · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ timeline · ship log",
    title: "What the lab has shipped.",
    stamp: "CHRONO",
    accent: "cyan",
    rightPrimary: "25",
    rightLabel: "entries in time order",
    bottomReceipt: "atomeons.com/timeline · CC-BY 4.0",
  });
}
