import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "Trust is given when a claim can be opened. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /trust · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ trust · posture",
    title: "Trust is given when a claim can be opened.",
    stamp: "POSTURE",
    accent: "cyan",
    rightPrimary: "10",
    rightLabel: "WILL-NOT clauses",
    bottomReceipt: "atomeons.com/trust · CC-BY 4.0",
  });
}
