import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "RAG Architectures and Failure Modes · AtomEons Atlas",
  description: "Retrieval-augmented generation done right — chunking, reranking, hybrid search, the lost-in-the-middle problem. Why most production RAG fails and what the working patterns look like in 2026.",
  alternates: { canonical: "https://atomeons.com/learn/atlas/rag-architectures" },
  openGraph: { title: "RAG Architectures · AtomEons Atlas", description: "Why most RAG fails — and what the patterns that actually work in production look like.", url: "https://atomeons.com/learn/atlas/rag-architectures", type: "article" },
};

export default function Page() {
  return (
    <main className="bg-[#08090B] text-[#F4F4F2] antialiased">
      <section className="border-b border-[#1F242B]">
        <div className="mx-auto max-w-4xl px-6 pt-20 pb-12 md:px-10 md:pt-28 md:pb-20">
          <p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#5A6068]"><Link href="/learn/atlas" className="hover:text-[#22F0D5]">§ Atlas</Link><span className="mx-3 text-[#1F242B]">·</span><span className="text-[#22F0D5]">Retrieval · LLM application architecture</span></p>
          <h1 className="mt-8 max-w-[26ch] text-balance text-[clamp(36px,6vw,72px)] font-extralight leading-[1.04] tracking-[-0.025em] text-[#F4F4F2]">RAG architectures — and why most of them fail</h1>
          <p className="mt-8 max-w-[64ch] font-serif text-[19px] leading-[1.55] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Retrieval-augmented generation puts the right documents in front of the model at the right moment. The architecture is simple; the failure modes are subtle; the production patterns that work are not the ones the demos show.</p>
        </div>
      </section>

      <article className="mx-auto max-w-3xl px-6 py-16 md:px-10 md:py-24 space-y-12">
        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What it is</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Retrieval-augmented generation (RAG) is the architectural pattern where, before sending a user query to an LLM, the application retrieves relevant context from an external knowledge store and concatenates it into the prompt. Lewis et al. published the original RAG paper at NeurIPS 2020 (arXiv:2005.11401), where retrieval and generation were jointly trained. The 2023-2026 production interpretation is looser: any system that grounds an LLM response in retrieved context counts as RAG, whether or not the retriever was trained alongside the generator.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The premise: LLM weights freeze at training time, but real applications need fresh data, private documents, and up-to-date facts. Fine-tuning is expensive and slow. RAG sidesteps both by injecting context dynamically.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>How it actually works</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The canonical pipeline has five stages. <em>Ingest</em>: documents are chunked into passages (typically 200-1000 tokens), each embedded into a vector by a model like OpenAI text-embedding-3-large or Voyage AI voyage-3. <em>Index</em>: vectors are stored in a vector database (Qdrant, pgvector, Pinecone, FAISS, Weaviate) with an ANN index — HNSW, IVF, or ScaNN are the dominant algorithms. <em>Query</em>: at runtime, the user query is embedded with the same model; the top-K nearest passages are retrieved by cosine similarity or dot product. <em>Rerank</em>: a more expensive cross-encoder (Cohere Rerank, BGE reranker) scores the top-K candidates against the actual query text and reorders them. <em>Generate</em>: the top-N reranked passages are stuffed into the LLM prompt as context.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The major refinements are <em>hybrid retrieval</em> (combining dense vector search with sparse keyword search — BM25 still wins for rare tokens and exact identifiers), <em>query rewriting</em> (asking the LLM to rephrase or expand the query before retrieval), <em>HyDE</em> (Hypothetical Document Embeddings — embed a generated answer to find passages similar to the answer rather than to the question), and <em>contextual retrieval</em> (Anthropic 2024 — prepending chunk-level context to each chunk before embedding, reducing failed retrievals by 49% in their published evaluation).</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The <em>lost-in-the-middle</em> problem (Liu et al, arXiv:2307.03172, 2023) is the hardest non-obvious failure mode: LLMs attend disproportionately to context at the beginning and end of their input window. A relevant passage placed in the middle of a 100K-token context is often ignored. The mitigation is to retrieve fewer, higher-quality passages and place them at the head or foot of the prompt — not to flood the context window.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Receipts</h2><ol className="space-y-4 font-serif text-[17px] leading-[1.6] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Lewis, Perez, Piktus et al. <em>Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks</em>. NeurIPS 2020. arXiv:2005.11401 — the original paper.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Liu, Lin, Hewitt et al. <em>Lost in the Middle: How Language Models Use Long Contexts</em>. TACL, arXiv:2307.03172, 2023.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Gao, Ma, Lin, Callan. <em>Precise Zero-Shot Dense Retrieval without Relevance Labels</em>. ACL 2023, arXiv:2212.10496 — HyDE.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Anthropic. <em>Introducing Contextual Retrieval</em>, September 2024 — <span className="font-mono text-[12px] text-[#5A6068]">anthropic.com/news/contextual-retrieval</span>. 49% reduction in failed retrievals when chunks are prefixed with their document context.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">MTEB — Massive Text Embedding Benchmark, Muennighoff et al. EMNLP 2023, arXiv:2210.07316. The standard leaderboard for embedding models.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">BEIR — Thakur et al. <em>BEIR: A Heterogeneous Benchmark for Zero-Shot Evaluation of Information Retrieval Models</em>. NeurIPS 2021, arXiv:2104.08663.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Hofstätter et al. <em>Improving Efficient Neural Ranking Models with Cross-Architecture Knowledge Distillation</em>, arXiv:2010.02666 — the rerank-after-retrieve pattern.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Edge, Trinh, Cheng et al (Microsoft). <em>From Local to Global: A Graph RAG Approach to Query-Focused Summarization</em>, arXiv:2404.16130, 2024 — GraphRAG, the structured-knowledge alternative.</li>
        </ol></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What practitioners do with it</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The working production pattern in 2026: hybrid retrieval (dense + BM25 with a weighted fusion), contextual chunking (Anthropic's pattern or similar), an actual reranker (Cohere or BGE), top-N truncation to 5-10 passages not 50, head-and-foot prompt placement to dodge lost-in-the-middle, and an eval harness that measures retrieval quality independently from generation quality (Ragas is the dominant open framework).</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Chunking strategy matters more than embedding model choice. Semantic chunking (split at section/paragraph boundaries) beats fixed-size chunking on long documents. Overlap between chunks (10-20% token overlap) improves recall for facts near boundaries. Most teams over-chunk and end up retrieving 50 fragments where 5 documents would have been better.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What it is NOT</h2><ul className="space-y-4 font-serif text-[17px] leading-[1.6] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not a replacement for fine-tuning.</strong> RAG injects facts; fine-tuning changes style, capabilities, and reasoning patterns. Use both for different problems.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not solved by long context alone.</strong> Gemini 2M and Claude 200K windows reduce the need for retrieval but don't eliminate it. Long-context models still suffer lost-in-the-middle; retrieval still matters for cost and latency.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not just &quot;embed and search.&quot;</strong> Production RAG is a pipeline with eval, rerank, query rewriting, and observability. Skipping any layer is where most demos fail when they scale.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not the same as agentic search.</strong> Agentic search (tool-using agents that issue search queries iteratively) is a more expensive, more flexible alternative. RAG retrieves once per turn; agents retrieve as needed.</li>
        </ul></section>

        <section className="space-y-3"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Further reading</h2><ul className="space-y-2 font-serif text-[16px] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li><a href="https://www.anthropic.com/news/contextual-retrieval" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">Anthropic · Contextual Retrieval</a></li>
          <li><a href="https://github.com/explodinggradients/ragas" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">Ragas (eval framework)</a></li>
          <li><a href="https://huggingface.co/spaces/mteb/leaderboard" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">MTEB embedding leaderboard</a></li>
          <li><Link href="/q/what-is-rag" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">AtomEons Q-page · What is RAG?</Link></li>
        </ul></section>

        <div className="border-t border-[#1F242B] pt-12"><div className="flex flex-wrap gap-4"><Link href="/learn/atlas" className="border border-[#1F242B] bg-[#0F1114] px-5 py-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[#F4F4F2] hover:border-[#22F0D5] hover:text-[#22F0D5]">← Back to Atlas</Link><Link href="/learn/atlas/long-context-engineering" className="font-mono text-[11px] uppercase tracking-[0.22em] text-[#9CA3AF] hover:text-[#22F0D5]">Long-context engineering →</Link></div></div>
      </article>
    </main>
  );
}
