import { renderNoirCard, ogSize, ogContentType } from "@/app/_components/og/NoirCard";

export const runtime = "edge";
export const alt =
  "What the lab is doing right now. · AtomEons Systems Laboratory";
export const size = ogSize;
export const contentType = ogContentType;

/**
 * /live · OG card · generated by .scripts/sweep-og-cards.mjs
 * Edit the CONFIG array in the script if you want to retune; this file
 * is otherwise a thin wrapper around the shared NoirCard renderer.
 */
export default function OG() {
  return renderNoirCard({
    section: "§ live · polling every 8s",
    title: "What the lab is doing right now.",
    stamp: "LIVE",
    accent: "pulse",
    rightPrimary: "8s",
    rightLabel: "poll interval · honest offline state",
    bottomReceipt: "atomeons.com/live · CC-BY 4.0",
  });
}
