import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Post-Quantum Cryptography Migration · AtomEons Cyber",
  description: "NIST finalized ML-KEM, ML-DSA, and SLH-DSA in August 2024. Harvest-now-decrypt-later makes the migration urgent regardless of when fault-tolerant quantum computers arrive. What CISOs are actually doing in 2025-2026.",
  alternates: { canonical: "https://atomeons.com/learn/cyber/post-quantum-crypto" },
  openGraph: { title: "Post-Quantum Cryptography · AtomEons Cyber", description: "NIST PQC standards, hybrid TLS, migration timelines.", url: "https://atomeons.com/learn/cyber/post-quantum-crypto", type: "article" },
};

export default function Page() {
  return (
    <main className="bg-[#08090B] text-[#F4F4F2] antialiased">
      <section className="border-b border-[#1F242B]"><div className="mx-auto max-w-4xl px-6 pt-20 pb-12 md:px-10 md:pt-28 md:pb-20">
        <p className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#5A6068]"><Link href="/learn/cyber" className="hover:text-[#22F0D5]">§ Cyber</Link><span className="mx-3 text-[#1F242B]">·</span><span className="text-[#22F0D5]">Cryptography · transition</span></p>
        <h1 className="mt-8 max-w-[26ch] text-balance text-[clamp(36px,6vw,72px)] font-extralight leading-[1.04] tracking-[-0.025em] text-[#F4F4F2]">Post-quantum cryptography — the migration is now</h1>
        <p className="mt-8 max-w-[64ch] font-serif text-[19px] leading-[1.55] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>NIST published the final FIPS standards in August 2024. Harvest-now-decrypt-later makes the timeline real today. The next decade of public-key cryptography migrates onto lattice-based algorithms — and the work to make that happen has started.</p>
      </div></section>

      <article className="mx-auto max-w-3xl px-6 py-16 md:px-10 md:py-24 space-y-12">
        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What it is</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Post-quantum cryptography (PQC) is the family of public-key cryptographic algorithms designed to resist attacks by a sufficiently powerful quantum computer. Today&apos;s widely deployed public-key crypto — RSA, Diffie-Hellman, ECDSA, ECDH — would be broken in polynomial time by Shor&apos;s algorithm running on a fault-tolerant quantum computer. No such computer exists publicly yet, but the consensus timeline among the people who fund this question seriously is &quot;sometime in the 2030s.&quot; That timeline is too close to wait.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The urgency multiplier is <em>harvest-now-decrypt-later</em>: a nation-state adversary collecting encrypted traffic today can store it indefinitely and decrypt it once a quantum capability exists. Data that needs confidentiality past 2035 needs to migrate now.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>How it actually works</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The NIST PQC standardization process ran from 2016 to 2024, evaluating 82 submissions. The August 2024 finalists became three FIPS standards. <em>FIPS 203 — ML-KEM</em> (Module-Lattice-based Key-Encapsulation Mechanism, derived from CRYSTALS-Kyber) is the key-establishment algorithm. <em>FIPS 204 — ML-DSA</em> (Module-Lattice-based Digital Signature Algorithm, derived from CRYSTALS-Dilithium) is the primary signature scheme. <em>FIPS 205 — SLH-DSA</em> (Stateless Hash-based Digital Signature Algorithm, derived from SPHINCS+) is the backup signature scheme based on hash functions instead of lattices, deliberately chosen so the world has a non-lattice option if lattice cryptography is later broken.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>A fourth algorithm, <em>FIPS 206 — FN-DSA</em> (FALCON-derived), is in final draft as of mid-2025 — smaller signatures than ML-DSA at the cost of harder implementation. NIST also ran a separate &quot;Round 4&quot; for additional KEM candidates not based on lattices; HQC was selected in March 2025 as a code-based backup KEM.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The deployment pattern is <em>hybrid</em>: rather than replacing classical crypto outright, current deployments combine a classical algorithm (X25519 for ECDH, ECDSA for signatures) with a PQC algorithm (ML-KEM for KEM, ML-DSA for signatures). The output of both is mixed into the final key/signature. If either algorithm survives, the combined scheme survives. Cloudflare deployed X25519+ML-KEM-768 (codename &quot;X25519MLKEM768&quot;) on all their HTTPS endpoints in March 2024; Chrome 116+, Firefox 124+, and Safari 17+ all negotiate it by default in 2026.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Receipts</h2><ol className="space-y-4 font-serif text-[17px] leading-[1.6] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">NIST FIPS 203, <em>Module-Lattice-Based Key-Encapsulation Mechanism Standard (ML-KEM)</em>. Published August 13, 2024. <span className="font-mono text-[12px] text-[#5A6068]">doi.org/10.6028/NIST.FIPS.203</span></li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">NIST FIPS 204, <em>Module-Lattice-Based Digital Signature Standard (ML-DSA)</em>. August 13, 2024. <span className="font-mono text-[12px] text-[#5A6068]">doi.org/10.6028/NIST.FIPS.204</span></li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">NIST FIPS 205, <em>Stateless Hash-Based Digital Signature Standard (SLH-DSA)</em>. August 13, 2024. <span className="font-mono text-[12px] text-[#5A6068]">doi.org/10.6028/NIST.FIPS.205</span></li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">National Security Memorandum NSM-10, <em>Promoting United States Leadership in Quantum Computing While Mitigating Risks to Vulnerable Cryptographic Systems</em>. May 4, 2022 — initiates the federal-systems PQC inventory + migration plans.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">CISA, NSA, NIST joint factsheet, <em>Quantum-Readiness: Migration to Post-Quantum Cryptography</em>. August 2023 — practical migration roadmap for critical infrastructure.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Shor, Peter W. <em>Polynomial-Time Algorithms for Prime Factorization and Discrete Logarithms on a Quantum Computer</em>. SIAM Journal on Computing 26(5), 1997 — the algorithm the migration is hedging against.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Cloudflare engineering blog, <em>The state of the post-quantum Internet</em> series, 2023-2025 — concrete deployment metrics for X25519MLKEM768 negotiation across the web.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">Open Quantum Safe project — <span className="font-mono text-[12px] text-[#5A6068]">openquantumsafe.org</span> — liboqs library + OQS-OpenSSL provider, the reference PQC implementations.</li>
          <li className="border-l-2 border-[#22F0D5]/40 pl-5">IETF Post-Quantum Use in Protocols (pquip) Working Group — coordinates PQC integration into TLS, SSH, IKEv2, X.509.</li>
        </ol></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What practitioners do with it</h2><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>The federal migration sequence under NSM-10 + CNSA 2.0 (NSA&apos;s Commercial National Security Algorithm Suite 2.0, September 2022) sets concrete deadlines: software/firmware signing must support PQC by 2025; public-key authentication for new National Security Systems by 2027; full transition by 2035.</p><p className="font-serif text-[18px] leading-[1.65] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Enterprise practitioners run a four-stage program. (1) <em>Crypto inventory</em>: where is RSA/ECDSA/ECDH used in this environment? Code, certs, HSMs, IoT devices, embedded firmware. (2) <em>Vendor pressure</em>: when will your IdP, your VPN, your HSM, your code-signing toolchain support hybrid PQC? (3) <em>Hybrid pilots</em>: deploy X25519MLKEM768 in TLS first; it&apos;s the lowest-risk because hybrid means classical security if either side breaks. (4) <em>Replace</em>: as ecosystems catch up, drop hybrid and move to pure PQC where appropriate. Most enterprises are still in stages 1-2 at end of 2026.</p></section>

        <section className="space-y-5"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>What it is NOT</h2><ul className="space-y-4 font-serif text-[17px] leading-[1.6] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not quantum cryptography.</strong> Post-quantum crypto runs on classical computers and defends against quantum attacks. Quantum cryptography (QKD) requires specialized photonic hardware. NSA recommends against QKD for national security systems.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not optional.</strong> The NSM-10 + CNSA 2.0 timelines bind federal procurement. Critical infrastructure sectors follow within years. Private enterprises with long-confidentiality data are already starting.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not a symmetric-crypto problem.</strong> AES-256 and SHA-3 are quantum-resistant (Grover&apos;s algorithm halves their effective security but 128-bit remaining strength is still safe). PQC is specifically a public-key migration.</li>
          <li className="border border-[#1F242B] bg-[#0F1114] p-5"><strong className="text-[#F4F4F2]">Not finished.</strong> ML-KEM, ML-DSA, SLH-DSA are standardized but new PQC algorithms are still being submitted, evaluated, and broken. NIST Round 4 + future rounds continue. Crypto-agility is the architectural answer — design systems that can swap algorithms.</li>
        </ul></section>

        <section className="space-y-3"><h2 className="font-serif text-[28px] font-light" style={{ fontFamily: "Newsreader, Georgia, serif" }}>Further reading</h2><ul className="space-y-2 font-serif text-[16px] text-[#9CA3AF]" style={{ fontFamily: "Newsreader, Georgia, serif" }}>
          <li><a href="https://csrc.nist.gov/projects/post-quantum-cryptography" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">NIST PQC project hub</a></li>
          <li><a href="https://www.cisa.gov/quantum" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">CISA Quantum-Readiness</a></li>
          <li><a href="https://openquantumsafe.org/" target="_blank" rel="noopener noreferrer" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">Open Quantum Safe (liboqs)</a></li>
          <li><Link href="/q/what-is-post-quantum-cryptography" className="text-[#22F0D5] underline decoration-[#1F242B] underline-offset-4 hover:decoration-[#22F0D5]">AtomEons Q-page · What is post-quantum cryptography?</Link></li>
        </ul></section>

        <div className="border-t border-[#1F242B] pt-12"><div className="flex flex-wrap gap-4"><Link href="/learn/cyber" className="border border-[#1F242B] bg-[#0F1114] px-5 py-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[#F4F4F2] hover:border-[#22F0D5] hover:text-[#22F0D5]">← Back to Cyber</Link></div></div>
      </article>
    </main>
  );
}
