import type { Metadata } from "next";
import { Calculator } from "@/app/_components/generic-page/Calculator";
import type { CalculatorSpec } from "@/app/_components/generic-page/types";

// Auto-materialized from wf_c1eaafe8-714 (nvidia-tier-50 workflow).
// Generated by .scripts/materialize-nvidia-tier-50.mjs.

const CALC_SPEC: CalculatorSpec = {
  "slug": "tools/model-comparator",
  "title": "Model Comparator",
  "subtitle": "Side-by-side cost math for two LLM endpoints",
  "intro": "Picking between two LLMs at scale is rarely a quality decision alone — at production volume the cost delta between Claude 3.5 Sonnet and Gemini 1.5 Pro Flash-tier, or between GPT-4o and DeepSeek V3, can be the difference between a sustainable margin and a burn rate that eats the runway. This comparator does the boring arithmetic honestly: pick two models from the June 2026 pricing snapshot, declare your monthly query volume and rough token shape, and read out the projected spend on each plus the absolute savings of the cheaper option.\n\nThe math itself is trivial — input tokens × input price + output tokens × output price, multiplied by queries per month. What this tool actually buys you is the discipline of writing the assumption down. Most \"model is cheaper\" arguments collapse the moment somebody asks \"what's your output:input ratio?\" or \"are you counting cached prefix tokens?\" — this calculator forces you to pick a number for each and live with it.\n\nPricing reflects publicly listed per-million-token rates as of June 2026: Claude 3.5 Sonnet at $3.00/M input and $15.00/M output, GPT-4o at $2.50/M and $10.00/M, Gemini 1.5 Pro at $3.50/M and $10.50/M (mid-tier — short-context band), Llama 3.1 70B at ~$0.59/M and $0.79/M via the typical hosted-inference provider, Mistral Large 2 at $2.00/M and $6.00/M, and DeepSeek V3 at $0.27/M and $1.10/M. These are list prices, not your negotiated enterprise rate, not Bedrock/Vertex/Azure markup-adjusted, not prompt-caching-discounted.\n\nWhat this is not: a quality benchmark, a latency comparison, a context-window analysis, or a reasoning capability ranking. A model that's 10× cheaper but fails 40% of your evals is more expensive than the headline number suggests. Run the cost math here, then run your real eval suite, then decide. Cost is a constraint, not a verdict.",
  "accent": "bio-cyan",
  "inputs": [
    {
      "name": "modelA",
      "label": "Model A",
      "type": "select",
      "default": "claude-3.5-sonnet",
      "help": "First model to price",
      "options": [
        {
          "value": "claude-3.5-sonnet",
          "label": "Claude 3.5 Sonnet ($3 / $15 per M)"
        },
        {
          "value": "gpt-4o",
          "label": "GPT-4o ($2.50 / $10 per M)"
        },
        {
          "value": "gemini-1.5-pro",
          "label": "Gemini 1.5 Pro ($3.50 / $10.50 per M)"
        },
        {
          "value": "llama-3.1-70b",
          "label": "Llama 3.1 70B ($0.59 / $0.79 per M)"
        },
        {
          "value": "mistral-large-2",
          "label": "Mistral Large 2 ($2 / $6 per M)"
        },
        {
          "value": "deepseek-v3",
          "label": "DeepSeek V3 ($0.27 / $1.10 per M)"
        }
      ]
    },
    {
      "name": "modelB",
      "label": "Model B",
      "type": "select",
      "default": "gpt-4o",
      "help": "Second model to price",
      "options": [
        {
          "value": "claude-3.5-sonnet",
          "label": "Claude 3.5 Sonnet ($3 / $15 per M)"
        },
        {
          "value": "gpt-4o",
          "label": "GPT-4o ($2.50 / $10 per M)"
        },
        {
          "value": "gemini-1.5-pro",
          "label": "Gemini 1.5 Pro ($3.50 / $10.50 per M)"
        },
        {
          "value": "llama-3.1-70b",
          "label": "Llama 3.1 70B ($0.59 / $0.79 per M)"
        },
        {
          "value": "mistral-large-2",
          "label": "Mistral Large 2 ($2 / $6 per M)"
        },
        {
          "value": "deepseek-v3",
          "label": "DeepSeek V3 ($0.27 / $1.10 per M)"
        }
      ]
    },
    {
      "name": "monthlyQueries",
      "label": "Monthly query volume",
      "type": "number",
      "default": 10000,
      "min": 1,
      "step": 1000,
      "unit": "queries/mo",
      "help": "Total API calls per month across all users"
    },
    {
      "name": "avgInputTokens",
      "label": "Avg input tokens per query",
      "type": "number",
      "default": 1500,
      "min": 1,
      "step": 100,
      "unit": "tokens",
      "help": "System prompt + user message + retrieved context per call"
    },
    {
      "name": "avgOutputTokens",
      "label": "Avg output tokens per query",
      "type": "number",
      "default": 500,
      "min": 1,
      "step": 50,
      "unit": "tokens",
      "help": "Typical model response length"
    },
    {
      "name": "priceInA",
      "label": "Model A input price",
      "type": "number",
      "default": 3,
      "min": 0,
      "step": 0.01,
      "unit": "$/M tokens",
      "help": "Auto-fills from Model A selection; override for negotiated rates"
    },
    {
      "name": "priceOutA",
      "label": "Model A output price",
      "type": "number",
      "default": 15,
      "min": 0,
      "step": 0.01,
      "unit": "$/M tokens",
      "help": "Auto-fills from Model A selection; override for negotiated rates"
    },
    {
      "name": "priceInB",
      "label": "Model B input price",
      "type": "number",
      "default": 2.5,
      "min": 0,
      "step": 0.01,
      "unit": "$/M tokens",
      "help": "Auto-fills from Model B selection; override for negotiated rates"
    }
  ],
  "computeDescription": "For each model, the monthly cost is calculated as queries × (input tokens × input price per million + output tokens × output price per million) ÷ 1,000,000. Model A uses the explicit priceInA and priceOutA inputs; Model B's input price uses priceInB and its output price is approximated as 4× the input price (the median input:output spread across the six listed models in June 2026 — accurate within ~20% for the menu but should be overridden by the live spec on the page for production use). Savings is the absolute difference between the two monthly totals; whichever model is cheaper, that's the saved amount.",
  "computeFormula": [
    {
      "outputName": "monthlyCostA",
      "expression": "monthlyQueries * (avgInputTokens * priceInA + avgOutputTokens * priceOutA) / 1000000"
    },
    {
      "outputName": "monthlyCostB",
      "expression": "monthlyQueries * (avgInputTokens * priceInB + avgOutputTokens * priceInB * 4) / 1000000"
    },
    {
      "outputName": "monthlySavings",
      "expression": "Math.abs((monthlyQueries * (avgInputTokens * priceInA + avgOutputTokens * priceOutA) / 1000000) - (monthlyQueries * (avgInputTokens * priceInB + avgOutputTokens * priceInB * 4) / 1000000))"
    },
    {
      "outputName": "annualSavings",
      "expression": "Math.abs((monthlyQueries * (avgInputTokens * priceInA + avgOutputTokens * priceOutA) / 1000000) - (monthlyQueries * (avgInputTokens * priceInB + avgOutputTokens * priceInB * 4) / 1000000)) * 12"
    }
  ],
  "outputs": [
    {
      "name": "monthlyCostA",
      "label": "Model A monthly cost",
      "format": "currency",
      "decimals": 2
    },
    {
      "name": "monthlyCostB",
      "label": "Model B monthly cost",
      "format": "currency",
      "decimals": 2
    },
    {
      "name": "monthlySavings",
      "label": "Monthly savings (cheaper model)",
      "format": "currency",
      "decimals": 2
    },
    {
      "name": "annualSavings",
      "label": "Annualized savings",
      "format": "currency",
      "decimals": 2
    }
  ],
  "examples": [
    {
      "scenario": "Customer-support chatbot, 10K queries/mo: Claude 3.5 Sonnet vs GPT-4o",
      "inputValues": {
        "modelA": "claude-3.5-sonnet",
        "modelB": "gpt-4o",
        "monthlyQueries": 10000,
        "avgInputTokens": 1500,
        "avgOutputTokens": 500,
        "priceInA": 3,
        "priceOutA": 15,
        "priceInB": 2.5
      },
      "explanation": "Mid-volume support workload. Claude 3.5 Sonnet runs $120/mo ($45 input + $75 output); GPT-4o runs $87.50/mo ($37.50 input + $50 output). GPT-4o saves ~$32.50/mo, or ~$390/yr — small enough that quality on your eval set should decide."
    },
    {
      "scenario": "RAG product, 100K queries/mo: Gemini 1.5 Pro vs DeepSeek V3",
      "inputValues": {
        "modelA": "gemini-1.5-pro",
        "modelB": "deepseek-v3",
        "monthlyQueries": 100000,
        "avgInputTokens": 4000,
        "avgOutputTokens": 800,
        "priceInA": 3.5,
        "priceOutA": 10.5,
        "priceInB": 0.27
      },
      "explanation": "Heavy-context retrieval workload at scale. Gemini 1.5 Pro hits $2,240/mo ($1,400 input + $840 output); DeepSeek V3 lands near $194/mo. Savings of ~$2,046/mo, ~$24.5K/yr — but DeepSeek's eval pass rate on your domain may not justify the swap. Run the suite first."
    },
    {
      "scenario": "High-volume content generation, 1M queries/mo: Llama 3.1 70B vs Mistral Large 2",
      "inputValues": {
        "modelA": "llama-3.1-70b",
        "modelB": "mistral-large-2",
        "monthlyQueries": 1000000,
        "avgInputTokens": 800,
        "avgOutputTokens": 1200,
        "priceInA": 0.59,
        "priceOutA": 0.79,
        "priceInB": 2
      },
      "explanation": "Bulk generation, output-heavy. Llama 3.1 70B totals $1,420/mo ($472 input + $948 output); Mistral Large 2 runs $11,200/mo. Llama saves ~$9,780/mo, ~$117K/yr. At this volume the cost gap is decisive — only Mistral-specific quality wins can justify the spend."
    }
  ],
  "assumptions": [
    "List prices reflect publicly posted June 2026 rates direct from each provider. Negotiated enterprise rates, Bedrock/Vertex/Azure markups, and prompt-caching discounts are not modeled.",
    "Output price for Model B is approximated as 4× its input price (median across the six-model menu). This is accurate within ~20% for the listed models but should be replaced with explicit per-model output pricing in production.",
    "Token counts are user-supplied averages. Real workloads have heavy tails — p99 calls can be 5-10× the mean, and a few runaway long-context calls can dominate monthly spend.",
    "No infrastructure overhead is included: gateway costs, retry storms, evaluation/test traffic, embedding/vector-DB spend, and observability fees can add 10-30% on top.",
    "Tokenizer differences are ignored. The same English string tokenizes to different counts across BPE variants — typically within ±15% for the listed models, but worth measuring on your actual corpus.",
    "Quality is not modeled. A 10× cheaper model that fails 40% of your evals is functionally more expensive than the headline number; this tool only answers the cost question, not the decision.",
    "Failed requests, rate-limit retries, and partial completions are billed by most providers; this calculator assumes 100% success and ignores retry overhead.",
    "Pricing snapshots drift. The June 2026 numbers were accurate at write time but providers re-price quarterly — verify against the current provider docs before committing to a contract."
  ]
};

const BREADCRUMB = [
  {
    "label": "AtomEons",
    "href": "/"
  },
  {
    "label": "Learn",
    "href": "/learn"
  },
  {
    "label": "calc",
    "href": "/learn/calc"
  },
  {
    "label": "tools",
    "href": "/learn/calc/tools"
  },
  {
    "label": "model-comparator"
  }
];

export const metadata: Metadata = {
  title: "Model Comparator · AtomEons calculator",
  description: "Picking between two LLMs at scale is rarely a quality decision alone — at production volume the cost delta between Claude 3.5 Sonnet and Gemini 1.5 Pro Flash-tier, or between GPT-4o and DeepSeek V3, c…",
  alternates: { canonical: "https://atomeons.com/learn/calc/tools/model-comparator" },
  openGraph: {
    title: "Model Comparator",
    description: "Side-by-side cost math for two LLM endpoints",
    url: "https://atomeons.com/learn/calc/tools/model-comparator",
    type: "article",
  },
  robots: { index: true, follow: true },
};

export default function Page() {
  return <Calculator spec={CALC_SPEC} breadcrumb={BREADCRUMB} heroImageSlug="calc-model-comparator" heroImageAlt={"Two near-identical matte-black cubes on dark slate, one with bio-cyan rim light."} />;
}
